---
title: "XGBoost readmission: development-only imputation and tuning"
description: |
  This notebook reconstructs readmission tuning using the five full-development
  missRanger imputations from notebook 00, preserving the original sample, two Optuna
  search stages and Pareto selection. It uses corrected Cox/Breslow net survival,
  arithmetic mean horizon Brier scores and an event-preserving encoding of zero
  follow-up times. Preflight, timing pilot and full execution are separate modes.
date: last-modified
author: "Andres Gonzalez-Santa Cruz"
bibliography: [_lit/refs.bib]
csl: "_lit/american-medical-association.csl" # (Optional: citation style, e.g., APA)
toc: true
toc-location: left
toc-float: true
format:
  html:
    css: ["_lib/styles.scss", "_lib/prediction_metrics_compact.css"]
    code-fold: true
    embed-resources: true
    theme: 
      - journal #https://quarto.org/docs/output-formats/html-themes-more.html
    fig-cap-location: top  
    toc: true
    toc-location: left
execute:
  error: false       # Stop at the first execution error
  echo: true         # Show code in the output
  warning: true      # Show warnings
  message: true      # Show messages from the code
  freeze: auto       # Use cache to speed up rendering if there are no changes
editor: source
execute-dir: project
lightbox: auto
---

## Execution scope
The investigator selected five imputations fitted once on **complete development**, without outcomes, before ML. This notebook reuses the completed datasets from notebook 00 for every CV fold and fits no imputer. Holdout rows are filtered out before predictor encoding or model fitting. The original cohort, participant split, two CV schemes, five imputations, hyperparameter ranges and both Optuna budgets are retained.
The prior readmission run fitted imputers within CV folds. Its models and scores are preserved as a superseded strategy and are not reused for this run. An archive of its notebook, HTML and execution record is available in the project documentation.
Approved corrections remain: training-only Cox/Breslow **net survival**, arithmetic mean Brier at 3, 6, 12, 36 and 60 months, and positive zero-time representation solely at the XGBoost signed-label interface. Immediate readmissions, original analytical times and participants are unchanged.
**Retained limitation of internal CV.** The five missRanger imputations were fitted once on the complete development sample, without outcome or follow-up variables, before survival-model cross-validation. Predictors from each internal validation fold therefore contributed to learning the imputer, although that fold is excluded from fitting its survival model. This CV does not independently validate the complete preprocessing-and-model-selection workflow. missRanger OOB diagnostics assess the imputation forests and do not remove this dependence. The direction and magnitude of its effect on the retained workflow have not been isolated by the available comparisons. The investigator explicitly retained this scope on 2026-10-05.
**Separate holdout boundary.** Holdout rows and outcomes were excluded from fitting the development imputers, ML tuning and SHAP screening. However, notebook 00's descriptive early-death audit inspected holdout outcomes, and inherited discovery decisions remain documented. Do not describe the entire historical and reconstructed workflow as wholly independent of the holdout.
Configuration explicitly selects preflight, a timing pilot or full tuning. Preflight verifies all five completed inputs and all fold/imputation encodings without fitting models. The investigator authorized adaptation and execution of notebooks 01 and 02 on 2026-10-03.
The investigator reported computational constraints as the original motivation for the horizon-based Brier criterion. No historical timing comparison was available. Averaging instead of integrating the same five calculated values does not itself materially reduce computation.

In [1]:
#| label: readm-config-and-environment
#| message: false
import time
t0 = time.perf_counter()
# Resolve all machine and input paths from the single project configuration.
import os, sys, json, platform, importlib.metadata, gc, hashlib, pickle, functools, datetime, html
from pathlib import Path
root = Path.cwd().resolve()
while not (root / "config.yml").is_file():
    if root.parent == root:
        raise FileNotFoundError("config.yml was not found.")
    root = root.parent
import yaml
config = yaml.safe_load((root / "config.yml").read_text(encoding="utf-8"))
settings = config["xgboost_readmission"]
threads = int(config["imputation"]["threads"])
for name in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS", "NUMEXPR_NUM_THREADS"):
    os.environ[name] = str(threads)
def resolve_path(value):
    path = Path(value)
    return path.resolve() if path.is_absolute() else (root / path).resolve()
def source_path(name):
    return resolve_path(config["sources"][name])
assert Path(sys.prefix).name == config["runtime"]["xgboost_environment"], "Select the configured surv kernel."
mode = settings["mode"]
assert mode in ("preflight", "pilot", "full"), "Invalid execution mode."
# Import the installed scientific stack after limiting native thread pools.
import numpy as np
import pandas as pd
import pyarrow as pa
pa.set_cpu_count(threads)
pa.set_io_thread_count(threads)
import psutil
import xgboost as xgb
from sksurv.linear_model.coxph import BreslowEstimator
from sksurv.metrics import brier_score, concordance_index_ipcw
from sksurv.util import Surv
from sksurv.nonparametric import CensoringDistributionEstimator
from sklearn.model_selection import StratifiedKFold
import optuna
from threadpoolctl import threadpool_limits, threadpool_info
from IPython.display import HTML, display
thread_limits = threadpool_limits(limits=threads)
seed = int(config["imputation"]["seed"])
np.random.seed(seed)
horizons = np.asarray(settings["horizons_months"], dtype=float)
assert settings["brier_aggregation"] == "arithmetic_mean"
assert settings["probability_target"] == "net_survival_breslow"
assert threads == 2 and np.all(np.diff(horizons) > 0)
written = []
run_started = time.perf_counter()
process = psutil.Process()
start_rss_gib = process.memory_info().rss / 2**30
# Keep exploratory tables scrollable without adding a widget dependency.
def show_table(data, caption):
    safe_caption = html.escape(caption)
    table = data.to_html(index=False, escape=True, float_format=lambda x: f"{x:.6f}")
    display(HTML(f'<div role="region" tabindex="0" aria-label="{safe_caption}" style="max-height:420px;overflow:auto;max-width:100%;border:1px solid #ddd;padding:0.4rem"><strong>{safe_caption}</strong>{table}</div>'))
show_table(pd.DataFrame({"Component": ["Kernel", "Seed", "Native threads", "Available RAM (GiB)", "Brier aggregation", "Probability target"], "Value": [f"Python {platform.python_version()} / {Path(sys.prefix).name}", seed, threads, round(psutil.virtual_memory().available / 2**30, 3), settings["brier_aggregation"], settings["probability_target"]]}), "Execution contract")
print(f"Elapsed: {(time.perf_counter() - t0) / 60:.3f} minutes")

C:\Users\andre\miniconda3\envs\surv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Elapsed: 0.023 minutes

In [2]:
#| label: readm-predict-net-survival
#| message: false
t0 = time.perf_counter()
# Estimate the Cox baseline from training outcomes and explicit XGBoost log-risk margins.
def predict_net_survival(y_train, margin_train, margin_valid, times):
    margin_train = np.asarray(margin_train, dtype=float)
    margin_valid = np.asarray(margin_valid, dtype=float)
    times = np.asarray(times, dtype=float)
    if margin_train.shape != (len(y_train),) or margin_valid.ndim != 1:
        raise ValueError("Training and validation margins must be one-dimensional and aligned.")
    if times.ndim != 1 or not len(times) or (np.diff(times) <= 0).any() or (times < 0).any():
        raise ValueError("Evaluation times must be nonnegative, ordered and unique.")
    if not all(np.isfinite(a).all() for a in (margin_train, margin_valid, times, y_train["time"])):
        raise ValueError("Nonfinite margins or follow-up times.")
    if not y_train["event"].any() or (y_train["time"] < 0).any() or times[-1] > y_train["time"].max():
        raise ValueError("Invalid training follow-up or unsupported evaluation horizon.")
    shift = margin_train.mean()
    with np.errstate(over="raise", invalid="raise", divide="raise"):
        baseline = BreslowEstimator().fit(margin_train - shift, y_train["event"], y_train["time"])
        indices = np.searchsorted(baseline.unique_times_, times, side="right")
        h0 = np.r_[0.0, baseline.cum_baseline_hazard_.y][indices]
        survival = np.exp(-np.exp(margin_valid - shift)[:, None] * h0[None, :])
    if not np.isfinite(survival).all() or ((survival < 0) | (survival > 1)).any():
        raise ValueError("Invalid predicted net survival.")
    if (np.diff(survival, axis=1) > 1e-12).any():
        raise ValueError("Predicted survival increases over time.")
    return survival
# Preserve the existing scorer and arithmetic aggregation without silent fallback values.
def mean_horizon_brier(y_train, y_valid, survival, times):
    times = np.asarray(times, dtype=float)
    if survival.shape != (len(y_valid), len(times)):
        raise ValueError("Survival predictions and validation outcomes are not aligned.")
    if not np.isfinite(survival).all() or ((survival < 0) | (survival > 1)).any():
        raise ValueError("Brier scoring requires finite probabilities between zero and one.")
    evaluated_times, scores = brier_score(y_train, y_valid, survival, times)
    if not np.array_equal(evaluated_times, times) or not np.isfinite(scores).all():
        raise ValueError("A requested Brier horizon could not be evaluated.")
    return float(np.mean(scores)), scores
# Preserve the original unweighted distance after Pareto selection.
def distance_to_ideal(c_index, mean_brier):
    c_index, mean_brier = np.asarray(c_index, dtype=float), np.asarray(mean_brier, dtype=float)
    if not np.isfinite(c_index).all() or not np.isfinite(mean_brier).all():
        raise ValueError("Selection metrics must be finite.")
    return np.sqrt((1 - c_index)**2 + mean_brier**2)
print("Net survival and mean Brier functions ready; no cohort model fitted.")
print(f"Elapsed: {(time.perf_counter() - t0) / 60:.3f} minutes")

Net survival and mean Brier functions ready; no cohort model fitted.
Elapsed: 0.000 minutes

In [3]:
#| label: readm-encode-zero-time-labels
#| message: false
t0 = time.perf_counter()
# Preserve events at time zero without altering the analytical follow-up times or shared ties.
def xgboost_cox_labels(y):
    times = np.asarray(y["time"], dtype=np.float32)
    events = np.asarray(y["event"], dtype=bool)
    epsilon = np.float32(settings["zero_time_label_months"])
    if not np.isfinite(times).all() or (times < 0).any() or not np.isfinite(epsilon) or epsilon <= 0:
        raise ValueError("XGBoost label times must be finite and nonnegative.")
    positive = times[times > 0]
    if len(positive) and epsilon >= positive.min():
        raise ValueError("The zero-time representation must precede every positive follow-up time.")
    represented = np.where(times == 0, epsilon, times)
    labels = np.where(events, represented, -represented).astype(np.float32)
    assert np.array_equal(labels > 0, events)
    assert np.array_equal(np.abs(labels[times > 0]), times[times > 0])
    return labels
print("Zero-time encoding changes only the XGBoost interface, for both events and censoring.")
print(f"Elapsed: {(time.perf_counter() - t0) / 60:.3f} minutes")

Zero-time encoding changes only the XGBoost interface, for both events and censoring.
Elapsed: 0.000 minutes

In [4]:
#| label: readm-synthetic-probability-controls
#| message: false
t0 = time.perf_counter()
# Check Breslow probabilities against an independent hand calculation with tied times.
synthetic_y = Surv.from_arrays([True, True, False, True], [1., 2., 2., 4.])
synthetic_risk = np.array([1., 2., 3., 4.])
synthetic_margin = np.log(synthetic_risk)
synthetic_valid_margin = np.log([0.1, 1., 80.])
synthetic_times = np.array([0., 1., 2., 3., 4.])
manual_hazard = np.array([0., 1 / 10, 1 / 10 + 1 / 9, 1 / 10 + 1 / 9, 1 / 10 + 1 / 9 + 1 / 4])
manual_survival = np.exp(-np.exp(synthetic_valid_margin)[:, None] * manual_hazard)
checked_survival = predict_net_survival(synthetic_y, synthetic_margin, synthetic_valid_margin, synthetic_times)
assert np.allclose(checked_survival, manual_survival, atol=1e-14, rtol=1e-12)
assert np.allclose(checked_survival, predict_net_survival(synthetic_y, synthetic_margin + 100, synthetic_valid_margin + 100, synthetic_times), atol=1e-14, rtol=1e-12)
# Without censoring, Brier must equal direct binary-status mean squared error.
uncensored_y = Surv.from_arrays([True] * 4, [1., 2., 4., 6.])
uncensored_times = np.array([1., 3., 5.])
uncensored_survival = predict_net_survival(uncensored_y, synthetic_margin, synthetic_margin, uncensored_times)
checked_mean, checked_scores = mean_horizon_brier(uncensored_y, uncensored_y, uncensored_survival, uncensored_times)
direct_scores = np.mean(((uncensored_y["time"][:, None] > uncensored_times).astype(float) - uncensored_survival)**2, axis=0)
assert np.allclose(checked_scores, direct_scores, atol=1e-14)
assert checked_mean == float(np.mean(checked_scores))
# Check immediate events, immediate censoring and unchanged follow-up ordering.
zero_control = Surv.from_arrays([True, False, True, False], [0., 0., 1., 2.])
zero_before = zero_control.copy()
zero_labels = xgboost_cox_labels(zero_control)
assert zero_labels[0] == -zero_labels[1] and zero_labels[0] > 0
assert np.array_equal(zero_control, zero_before)
assert np.array_equal(np.argsort(np.abs(zero_labels), kind="stable"), np.argsort(zero_control["time"], kind="stable"))
# Refuse unsupported horizons and invalid probabilities instead of substituting optimistic scores.
try:
    predict_net_survival(synthetic_y, synthetic_margin, synthetic_valid_margin, np.array([5.]))
except ValueError:
    unsupported_rejected = True
else:
    raise AssertionError("An unsupported horizon was accepted.")
try:
    mean_horizon_brier(uncensored_y, uncensored_y, np.full((4, 3), 1.1), uncensored_times)
except ValueError:
    invalid_rejected = True
else:
    raise AssertionError("An invalid probability was accepted.")
show_table(pd.DataFrame({"Control": ["Breslow versus hand calculation: maximum absolute error", "Brier versus direct MSE: maximum absolute error", "Common margin shift", "Bounded, nonincreasing survival", "Invalid probabilities and unsupported horizon"], "Result": [f"{np.max(np.abs(checked_survival - manual_survival)):.3g}", f"{np.max(np.abs(checked_scores - direct_scores)):.3g}", "passed", "passed", "rejected"]}), "Synthetic controls only; not study results")
print(f"Elapsed: {(time.perf_counter() - t0) / 60:.3f} minutes")

Elapsed: 0.000 minutes

## Historical selection criterion
Pareto dominance has no explicit weighting: a candidate is dominated when another has at least as high C and at least as low mean Brier, with one strict improvement. Candidates are subsequently ranked by the original unweighted distance to the ideal point. The following table describes the saved historical candidates; it is not a new performance estimate.

In [5]:
#| label: readm-verify-historical-selection
#| message: false
t0 = time.perf_counter()
# Recompute the selection rule from the original saved final-candidate table.
reference = pd.read_csv(source_path("xgboost_readmission_reference"))
c_column = "Phase2_Multi_Horizon_C_Index"
b_column = "Phase2_Aalen_Johansen_Brier_Score"
assert reference[["trial_id", c_column, b_column, "Distance_to_Ideal"]].notna().all().all()
reference["recomputed_distance"] = distance_to_ideal(reference[c_column], reference[b_column])
assert np.allclose(reference["recomputed_distance"], reference["Distance_to_Ideal"], atol=1e-14)
reference["c_squared_term"] = (1 - reference[c_column])**2
reference["brier_squared_term"] = reference[b_column]**2
reference["c_share_percent"] = 100 * reference["c_squared_term"] / (reference["c_squared_term"] + reference["brier_squared_term"])
reference["rank_distance"] = reference["recomputed_distance"].rank(method="min")
reference["rank_c"] = reference[c_column].rank(ascending=False, method="min")
historical_winner = reference.loc[reference["recomputed_distance"].idxmin()]
assert int(historical_winner["trial_id"]) == int(reference.loc[reference[c_column].idxmax(), "trial_id"])
show_table(reference[["trial_id", c_column, b_column, "c_share_percent", "rank_distance", "rank_c"]].sort_values("rank_distance"), "Saved historical candidates: original mislabeled Brier column retained for traceability")
print("The C share describes squared-distance components; it is not an algorithm weight.")
print(f"Elapsed: {(time.perf_counter() - t0) / 60:.3f} minutes")

The C share describes squared-distance components; it is not an algorithm weight.
Elapsed: 0.000 minutes

## Approved zero-time encoding
Immediate readmissions remain events. A positive numerical representation is used only when constructing the signed XGBoost labels; the analytical follow-up times, baseline-hazard estimation, IPCW, evaluation horizons and exported endpoints retain their original values. The same representation is applied to zero-time events and censoring before assigning the sign, preserving their shared tie.

In [6]:
#| label: readm-audit-zero-time-labels
#| message: false
t0 = time.perf_counter()
# Audit the original signed-time rule using development rows only.
endpoint_columns = ["original_row_id", "is_train", "readmit_event", "readmit_time_from_disch_m"]
development_endpoint = pd.read_parquet(source_path("clean_completed_reference"), columns=endpoint_columns, filters=[("is_train", "=", True)])
assert development_endpoint["is_train"].all() and development_endpoint["original_row_id"].is_unique
assert development_endpoint[endpoint_columns].notna().all().all()
y_development = Surv.from_arrays(development_endpoint["readmit_event"].eq(1), development_endpoint["readmit_time_from_disch_m"])
assert np.isfinite(y_development["time"]).all() and (y_development["time"] >= 0).all()
original_xgb_labels = np.where(y_development["event"], y_development["time"], -y_development["time"]).astype(np.float32)
lost_events = y_development["event"] & ~(original_xgb_labels > 0)
zero_time = y_development["time"] == 0
assert np.array_equal(lost_events, y_development["event"] & zero_time)
label_check = pd.DataFrame({"Check": ["Development participants", "Observed readmissions at time zero", "Censored observations at time zero", "Recorded events lost by signed-time encoding"], "Count": [len(y_development), int((zero_time & y_development["event"]).sum()), int((zero_time & ~y_development["event"]).sum()), int(lost_events.sum())]})
show_table(label_check, "Original label audit; analytical outcomes unchanged")
corrected_xgb_labels = xgboost_cox_labels(y_development)
assert np.array_equal(corrected_xgb_labels > 0, y_development["event"])
assert np.array_equal(np.argsort(np.abs(original_xgb_labels), kind="stable"), np.argsort(np.abs(corrected_xgb_labels), kind="stable"))
assert np.array_equal(original_xgb_labels[~zero_time], corrected_xgb_labels[~zero_time])
print(f"Event mismatches after the approved interface correction: {np.count_nonzero((corrected_xgb_labels > 0) != y_development['event'])}")
print("Analytical times, participants, events and time-zero ties are unchanged.")
print(f"Elapsed: {(time.perf_counter() - t0) / 60:.3f} minutes")

Event mismatches after the approved interface correction: 0
Analytical times, participants, events and time-zero ties are unchanged.
Elapsed: 0.001 minutes

## Completed development and internal partitions
Python reads the five completed Parquet inputs from notebook 00, with an explicit development-only filter. Identity, row order, outcomes, observed programme and absence of missing predictors are checked across imputations. Identifiers, centre metadata and all future outcomes are excluded from predictor encoding.
The initial search retains treatment-plan stratification; the informed search retains treatment-plan by readmission-event stratification. Both use the original seed and five folds. Actual memberships must match the saved reference manifest before any model is fitted.

In [7]:
#| label: readm-completed-data-and-artifacts
#| message: false
t0 = time.perf_counter()
# Use deterministic content fingerprints and dated, reusable artifacts.
object_dir = resolve_path(config["paths"]["objects"])
table_dir = resolve_path(config["paths"]["tables"])
assert object_dir.is_dir() and table_dir.is_dir()
def file_sha256(path):
    with Path(path).open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()
def fingerprint(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, ensure_ascii=True, allow_nan=False).encode()).hexdigest()[:12]
def artifact_path(prefix, signature, suffix):
    matches = sorted(object_dir.glob(f"{prefix}_????-??-??_{signature}{suffix}"))
    if len(matches) > 1:
        raise RuntimeError(f"Multiple cache artifacts match {prefix} / {signature}.")
    return matches[0] if matches else object_dir / f"{prefix}_{datetime.date.today().isoformat()}_{signature}{suffix}"
def save_pickle(value, path):
    temporary = path.with_suffix(path.suffix + ".partial")
    with temporary.open("wb") as stream:
        pickle.dump(value, stream, protocol=5)
    temporary.replace(path)
    if path not in written:
        written.append(path)
def notebook_code(path, labels):
    notebook = json.loads(path.read_text(encoding="utf-8"))
    selected = {}
    for cell in notebook["cells"]:
        source = "".join(cell.get("source", []))
        for label in labels:
            if source.startswith(f"#| label: {label}\n"):
                if label in selected:
                    raise ValueError(f"Duplicate notebook label: {label}")
                selected[label] = source
    if set(selected) != set(labels):
        raise ValueError("Required notebook code could not be found.")
    return selected
# Load only the five full-development imputations already produced by notebook 00.
completed_paths = [resolve_path(value) for value in config["sources"]["clean_completed_datasets"]]
assert len(completed_paths) == int(config["imputation"]["n_imputations"]) == 5
assert len(set(completed_paths)) == 5 and completed_paths[0] == source_path("clean_completed_reference")
completed_hashes = [file_sha256(path) for path in completed_paths]
metadata_names = ["original_row_id", "hash_key", "legacy_row_id", "is_train", "center_id"]
outcome_names = ["readmit_time_from_disch_m", "readmit_event", "death_time_from_disch_m", "death_event", "readmit_time_from_adm_m", "death_time_from_adm_m"]
development_data = pd.read_parquet(completed_paths[0], filters=[("is_train", "=", True)])
assert development_data["is_train"].all() and development_data["original_row_id"].is_unique
pd.testing.assert_frame_equal(development_data[endpoint_columns], development_endpoint)
predictor_names = [name for name in development_data if name not in metadata_names + outcome_names]
assert len(predictor_names) == 39 and not set(predictor_names).intersection(metadata_names + outcome_names)
historical_exclusions = ["num_trat_ant", "age_subs_onset_rec2", "phys_dx_instudy"]
assert set(historical_exclusions).issubset(predictor_names)
retained_predictors = [name for name in predictor_names if name not in historical_exclusions]
# Keep one completed development dataset in memory; holdout rows never enter model inputs.
@functools.lru_cache(maxsize=1)
def completed_development(imputation):
    if imputation not in range(1, 6):
        raise ValueError("Imputation index must be between one and five.")
    path = completed_paths[imputation - 1]
    if file_sha256(path) != completed_hashes[imputation - 1]:
        raise RuntimeError("A completed input changed during this run.")
    data = pd.read_parquet(path, filters=[("is_train", "=", True)])
    assert list(data.columns) == list(development_data.columns)
    pd.testing.assert_frame_equal(data[metadata_names + outcome_names], development_data[metadata_names + outcome_names])
    assert data["is_train"].all() and data["original_row_id"].is_unique
    assert not data[predictor_names].isna().any().any()
    assert np.array_equal(data["plan_type_corr"], development_data["plan_type_corr"])
    return data
# Reuse the same prepared values in every fold, while fitting encoding on training rows only.
@functools.lru_cache(maxsize=1)
def encoded_fold(scheme, fold, imputation):
    data = completed_development(imputation)
    training, validation = splits[scheme][fold - 1]
    x_train, x_valid = encode_fold(data.iloc[training], data.iloc[validation])
    metadata = {"imputation": imputation, "source": completed_paths[imputation - 1].relative_to(root).as_posix(), "fit_scope": "complete_development_before_cv", "refitted": False}
    return x_train, x_valid, y_development[training], y_development[validation], metadata
input_audit = []
for imputation in range(1, 6):
    completed = completed_development(imputation)
    input_audit.append({"Imputation": imputation, "Development rows": len(completed), "Imputation predictors": len(predictor_names), "Retained ML predictors": len(retained_predictors), "Missing predictors": int(completed[predictor_names].isna().sum().sum()), "Source": completed_paths[imputation - 1].relative_to(root).as_posix()})
del completed
completed_development.cache_clear()
show_table(pd.DataFrame(input_audit), "Verified complete-development imputations from notebook 00")
print("No R subprocess or imputation fit is run here. Metadata, including center_id, never enters the predictor matrix.")
print(f"Elapsed: {(time.perf_counter() - t0) / 60:.3f} minutes")

No R subprocess or imputation fit is run here. Metadata, including center_id, never enters the predictor matrix.
Elapsed: 0.020 minutes

In [8]:
#| label: readm-freeze-and-check-folds
#| message: false
t0 = time.perf_counter()
# Preserve the original fold memberships; the imputations are already complete.
plan_codes = development_data["plan_type_corr"].map({"pg-pab": 0, "pg-pr": 1, "m-pr": 2, "pg-pai": 3, "m-pai": 4})
assert plan_codes.notna().all()
strata = {"plan": plan_codes.to_numpy(dtype=int), "dual": plan_codes.to_numpy(dtype=int) * 10 + y_development["event"].astype(int)}
fold_manifest = pd.DataFrame({"original_row_id": development_data["original_row_id"].to_numpy()})
splits = {}
for scheme, labels in strata.items():
    counts = pd.Series(labels).value_counts()
    if len(counts) < 2 or counts.min() < 5:
        raise ValueError("The fixed cohort no longer supports the original stratification.")
    splits[scheme] = list(StratifiedKFold(n_splits=5, shuffle=True, random_state=seed).split(np.zeros(len(labels)), labels))
    membership = np.zeros(len(labels), dtype=np.int8)
    for fold, (training, validation) in enumerate(splits[scheme], start=1):
        assert not np.intersect1d(training, validation).size
        membership[validation] = fold
    assert np.all((membership >= 1) & (membership <= 5))
    fold_manifest[f"{scheme}_fold"] = membership
# Anchor the actual memberships to the previous manifest before any new model fit.
previous_folds = pd.read_parquet(source_path("readmission_fold_reference"))
pd.testing.assert_frame_equal(fold_manifest, previous_folds[fold_manifest.columns])
data_contract = {"imputation_fit_scope": "complete_development_before_cv", "completed_sha256": completed_hashes, "imputation": config["imputation"], "seed": seed, "manifest_sha256": hashlib.sha256(fold_manifest.to_csv(index=False).encode()).hexdigest(), "loader_code": notebook_code(source_path("readmission_notebook"), ["readm-completed-data-and-artifacts"])}
data_signature = fingerprint(data_contract)
manifest_path = artifact_path("xgb_readm_fold_manifest", data_signature, ".parquet")
if manifest_path.exists():
    pd.testing.assert_frame_equal(pd.read_parquet(manifest_path), fold_manifest)
else:
    manifest_path.write_bytes(fold_manifest.to_parquet(index=False))
    pd.testing.assert_frame_equal(pd.read_parquet(manifest_path), fold_manifest)
    written.append(manifest_path)
# Check censoring support at every requested horizon without fitting a survival model.
support_rows = []
for scheme, scheme_splits in splits.items():
    for fold, (training, validation) in enumerate(scheme_splits, start=1):
        y_train, y_valid = y_development[training], y_development[validation]
        censoring = CensoringDistributionEstimator().fit(y_train)
        assert np.all(censoring.predict_proba(horizons) > 0)
        assert np.isfinite(censoring.predict_ipcw(y_valid)).all()
        for horizon in horizons:
            assert np.isfinite(censoring.predict_ipcw(y_valid[y_valid["time"] < horizon])).all()
        assert y_valid["time"].min() <= horizons[0] and horizons[-1] < y_valid["time"].max()
        support_rows.append({"Scheme": scheme, "Fold": fold, "Training": len(training), "Validation": len(validation), "Changed memberships": 0, "IPCW support": "passed"})
show_table(pd.DataFrame(support_rows), "Original internal validation partitions, unchanged")
print("Every CV fold uses values prepared from complete development. Internal CV shares this preprocessing.")
print(f"Elapsed: {(time.perf_counter() - t0) / 60:.3f} minutes")

Every CV fold uses values prepared from complete development. Internal CV shares this preprocessing.
Elapsed: 0.007 minutes

## Predictor encoding
Ordinal mappings, dummy reference categories and the first-substance grouping follow the original notebook. Category levels and zero-variance removal are determined in each training fold; validation uses that frozen encoding. Unmapped categories raise an error rather than receiving an unreported replacement. Imputation itself has already been completed on all development rows in notebook 00.

In [9]:
#| label: readm-training-only-encoding
#| message: false
t0 = time.perf_counter()
# Preserve the study-defined ordinal scores and dummy references.
clinical_levels = {"logro minimo": 2, "logro intermedio": 1, "logro alto": 0}
ordered_mappings = {name: clinical_levels for name in ["evaluacindelprocesoteraputico", "eva_consumo", "eva_fam", "eva_relinterp", "eva_ocupacion", "eva_sm", "eva_fisica", "eva_transgnorma"]}
ordered_mappings.update({"tenure_status_household": {"illegal settlement": 4, "stays temporarily with a relative": 3, "others": 2, "renting": 1, "owner/transferred dwellings/pays dividends": 0}, "urbanicity_cat": {"1.Rural": 2, "2.Mixed": 1, "3.Urban": 0}, "prim_sub_freq_rec": {"1.\u22641 day/wk": 0, "2.2\u20136 days/wk": 1, "3.Daily": 2}, "ed_attainment_corr": {"3-Completed primary school or less": 2, "2-Completed high school or less": 1, "1-More than high school": 0}})
dummy_reference = {"sex_rec": "man", "plan_type_corr": "pg-pab", "marital_status_rec": "married/cohabiting", "cohabitation": "alone", "sub_dep_icd10_status": "hazardous consumption", "tr_outcome": "completion", "adm_motive": "spontaneous consultation", "tipo_de_vivienda_rec2": "formal housing", "occupation_condition_corr24": "employed", "any_violence": "0.No domestic violence/sex abuse", "first_sub_used": "marijuana", "primary_sub_mod": "marijuana"}
grouped_substances = ["opioids", "others", "hallucinogens", "inhalants", "tranquilizers/hypnotics", "amphetamine-type stimulants"]
def encode_fold(training, validation):
    training, validation = training[retained_predictors].copy(), validation[retained_predictors].copy()
    if training.isna().any().any() or validation.isna().any().any():
        raise ValueError("Model encoding requires completed predictors.")
    for name, mapping in ordered_mappings.items():
        for data in (training, validation):
            values = data[name].astype(str).str.strip()
            if not values.isin(mapping).all():
                raise ValueError(f"Unknown ordinal category: {name}")
            data[name] = values.map(mapping).astype(float)
    for data in (training, validation):
        data["first_sub_used"] = data["first_sub_used"].replace(dict.fromkeys(grouped_substances, "other"))
    for name in training:
        if pd.api.types.is_numeric_dtype(training[name]) or pd.api.types.is_bool_dtype(training[name]):
            continue
        observed = training[name].astype(str).str.strip()
        reference_level = dummy_reference.get(name)
        levels = sorted(observed.unique().tolist())
        if reference_level is not None:
            if reference_level not in levels:
                raise ValueError(f"Missing training reference level: {name}")
            levels = [reference_level] + [level for level in levels if level != reference_level]
        if not validation[name].astype(str).str.strip().isin(levels).all():
            raise ValueError(f"Unseen model-encoding category: {name}")
        for data in (training, validation):
            data[name] = pd.Categorical(data[name].astype(str).str.strip(), categories=levels)
    training = pd.get_dummies(training, drop_first=True, dtype=float)
    validation = pd.get_dummies(validation, drop_first=True, dtype=float)
    keep = training.columns[training.nunique(dropna=False) > 1].tolist()
    import re
    names = [re.sub(r"[^\w]+", "_", name.lower()).strip("_") for name in keep]
    if len(names) != len(set(names)) or not names:
        raise ValueError("Encoded feature names must be unique and nonempty.")
    training, validation = training[keep].astype(np.float32), validation[keep].astype(np.float32)
    training.columns = validation.columns = names
    assert np.isfinite(training.to_numpy()).all() and np.isfinite(validation.to_numpy()).all()
    return training, validation
# Exercise encoding with completed training rows; these checks produce no CV results.
check_training = development_data.iloc[next(iter(splits.values()))[0][0]][retained_predictors]
check_validation = check_training.iloc[:3].copy()
encoded_check, encoded_valid = encode_fold(check_training, check_validation)
changed_validation = check_validation.copy()
changed_validation["adm_age_rec3"] = changed_validation["adm_age_rec3"] + 100
unchanged_training, _ = encode_fold(check_training, changed_validation)
pd.testing.assert_frame_equal(encoded_check, unchanged_training)
bad_validation = check_validation.copy()
bad_validation["ed_attainment_corr"] = "__unknown__"
try:
    encode_fold(check_training, bad_validation)
except ValueError:
    pass
else:
    raise AssertionError("An unknown ordinal category was silently accepted.")
del check_training, check_validation, changed_validation, bad_validation, encoded_check, encoded_valid, unchanged_training
print("Training encoding is invariant to validation changes; unknown ordinal values are rejected.")
print(f"Elapsed: {(time.perf_counter() - t0) / 60:.3f} minutes")

Training encoding is invariant to validation changes; unknown ordinal values are rejected.
Elapsed: 0.012 minutes

## Reusing completed inputs and model scores
The five completed datasets stay on disk; at most one extra completed dataset and one encoded fold are cached in memory. No fold-specific imputer, OOB table or copied completed matrix is generated. The full-development forests retained by notebook 00 remain available for frozen application.
Data and method fingerprints include the approved imputation scope, completed-input hashes and fixed fold memberships. The same parameters, imputation and fold reuse their saved scores during rescoring. Earlier scores from fold-wise or historical full-cohort imputation cannot match the new contract. Metric errors stop execution rather than becoming C=0.5 or Brier=0.25.

In [10]:
#| label: readm-fold-cache-and-evaluation
#| message: false
t0 = time.perf_counter()
# Score models using the completed-development loader shared with notebook 02.
fixed_xgb = {"objective": "survival:cox", "eval_metric": "cox-nloglik", "tree_method": "hist", "device": "cpu", "nthread": threads, "seed": seed}
initial_ranges = {"learning_rate": ("float", 0.002, 0.035, True), "max_depth": ("int", 4, 9, False), "min_child_weight": ("int", 3, 30, False), "subsample": ("float", 0.60, 0.90, False), "colsample_bytree": ("float", 0.40, 0.70, False), "reg_alpha": ("float", 0.001, 2.0, True), "reg_lambda": ("float", 0.1, 10.0, True), "gamma": ("float", 0.01, 2.0, True)}
refined_ranges = {"learning_rate": ("float", 0.0025, 0.012, True), "max_depth": ("int", 4, 9, False), "min_child_weight": ("int", 4, 30, False), "subsample": ("float", 0.54, 0.92, False), "colsample_bytree": ("float", 0.45, 0.66, False), "reg_alpha": ("float", 0.0001, 2.0, True), "reg_lambda": ("float", 0.1, 3.5, True), "gamma": ("float", 0.2, 2.0, False)}
param_names = list(initial_ranges)
def native_params(values):
    return {name: int(values[name]) if name in ("max_depth", "min_child_weight") else float(values[name]) for name in param_names}
method_labels = ["readm-completed-data-and-artifacts", "readm-freeze-and-check-folds", "readm-predict-net-survival", "readm-encode-zero-time-labels", "readm-training-only-encoding", "readm-fold-cache-and-evaluation", "readm-optuna-and-pareto"]
model_contract = {"data_signature": data_signature, "data_contract": data_contract, "retained_predictors": retained_predictors, "horizons": horizons.tolist(), "probability_target": settings["probability_target"], "brier_aggregation": settings["brier_aggregation"], "zero_time_label_months": settings["zero_time_label_months"], "fixed_xgb": fixed_xgb, "rounds": 1500, "early_stopping": 30, "budgets": {"initial": 100, "refined": 50, "rescore_top_k": [20, 10], "seed_top": 7, "folds": 5, "imputations": 5}, "prediction_trees": "all_returned_trees_as_in_original", "initial_ranges": initial_ranges, "refined_ranges": refined_ranges, "code": notebook_code(source_path("readmission_notebook"), method_labels), "versions": {name: importlib.metadata.version(name) for name in ["numpy", "pandas", "xgboost", "optuna", "scikit-learn", "scikit-survival"]}}
model_signature = fingerprint(model_contract)
score_path = artifact_path("xgb_readm_fold_scores", model_signature, ".pkl")
if score_path.exists():
    with score_path.open("rb") as stream:
        score_cache = pickle.load(stream)
    assert score_cache["contract"] == model_contract
else:
    score_cache = {"contract": model_contract, "scores": {}}
new_model_fits = 0
def evaluate_fold(params, scheme, fold, imputation):
    global new_model_fits
    params = native_params(params)
    key = fingerprint({"params": params, "scheme": scheme, "fold": fold, "imputation": imputation})
    if key in score_cache["scores"]:
        return score_cache["scores"][key]
    if mode == "preflight":
        raise RuntimeError("Preflight cannot fit XGBoost models.")
    x_train, x_valid, y_train, y_valid, imputation_metadata = encoded_fold(scheme, fold, imputation)
    model_started = time.perf_counter()
    d_train = xgb.DMatrix(x_train, label=xgboost_cox_labels(y_train), nthread=threads)
    d_valid = xgb.DMatrix(x_valid, label=xgboost_cox_labels(y_valid), nthread=threads)
    booster = xgb.train(dict(fixed_xgb, **params), d_train, num_boost_round=1500, evals=[(d_valid, "validation")], early_stopping_rounds=30, verbose_eval=False)
    fitting_seconds = time.perf_counter() - model_started
    # Preserve the original all-returned-tree prediction policy after early stopping.
    rounds = booster.num_boosted_rounds()
    tree_range = (0, rounds)
    risk_valid = booster.predict(d_valid, iteration_range=tree_range)
    margin_train = booster.predict(d_train, output_margin=True, iteration_range=tree_range)
    margin_valid = booster.predict(d_valid, output_margin=True, iteration_range=tree_range)
    survival = predict_net_survival(y_train, margin_train, margin_valid, horizons)
    c_horizons = [float(concordance_index_ipcw(y_train, y_valid, risk_valid, tau=horizon)[0]) for horizon in horizons]
    global_c = float(concordance_index_ipcw(y_train, y_valid, risk_valid)[0])
    mean_brier, brier_horizons = mean_horizon_brier(y_train, y_valid, survival, horizons)
    if not np.isfinite(c_horizons + [global_c, mean_brier]).all():
        raise ValueError("A fold metric was nonfinite.")
    result = {"params": params, "scheme": scheme, "fold": fold, "imputation": imputation, "C": float(np.mean(c_horizons)), "mean_Brier": mean_brier, "global_C": global_c, "C_by_horizon": c_horizons, "Brier_by_horizon": brier_horizons.tolist(), "best_iteration": int(booster.best_iteration), "returned_rounds": rounds, "features": list(x_train.columns), "fit_seconds": fitting_seconds, "model_and_scoring_seconds": time.perf_counter() - model_started, "imputation_source": imputation_metadata["source"], "imputation_fit_scope": imputation_metadata["fit_scope"], "imputation_refitted": False}
    score_cache["scores"][key] = result
    save_pickle(score_cache, score_path)
    new_model_fits += 1
    del booster, d_train, d_valid, margin_train, margin_valid, risk_valid, survival
    gc.collect()
    return result
show_table(pd.DataFrame({"Parameter": param_names, "Initial_range": [str(initial_ranges[name][1:3]) for name in param_names], "Refined_range": [str(refined_ranges[name][1:3]) for name in param_names]}), "Original search ranges")
print(f"Elapsed: {(time.perf_counter() - t0) / 60:.3f} minutes")

Elapsed: 0.000 minutes

## Optuna and all-imputation Pareto rescoring
The initial search uses 100 trials; the informed search uses 50 trials including up to seven configurations from the newly rescored initial candidates. Each trial cycles through one of five imputations; candidate rescoring uses all five imputations and five folds. This assignment is balanced and deterministic, rather than a random imputation draw.
Both samplers now have an explicit seed and studies run sequentially with two native XGBoost threads. The original initial sampler had no explicit seed. The original pruning thresholds and unweighted distance are retained. Informed seed configurations outside its narrower random-search bounds remain eligible, as in the original.
Study and score checkpoints are saved after completed steps. The exploratory grid and the unreported optimism bootstrap are not rerun; their removal is documented.

In [11]:
#| label: readm-optuna-and-pareto
#| message: false
t0 = time.perf_counter()
# Preserve Optuna budgets, candidate limits and pruning; checkpoint sampler state for exact resumption.
def pareto_table(study):
    rows = [{"trial_id": trial.number, "C": trial.values[0], "mean_Brier": trial.values[1], **native_params(trial.params)} for trial in study.best_trials]
    if not rows:
        raise RuntimeError("No complete Pareto candidate is available.")
    table = pd.DataFrame(rows)
    table["Distance_to_Ideal"] = distance_to_ideal(table["C"], table["mean_Brier"])
    return table.sort_values("Distance_to_Ideal", kind="stable").reset_index(drop=True)
def optimize_stage(scheme, trial_budget, seed_configs=()):
    if mode != "full":
        raise RuntimeError("Full tuning requires execution mode full.")
    ranges = initial_ranges if scheme == "plan" else refined_ranges
    minimum_folds, minimum_c = (2, 0.55) if scheme == "plan" else (3, 0.58)
    study_path = artifact_path(f"xgb_readm_optuna_{scheme}", model_signature, ".pkl")
    if study_path.exists():
        with study_path.open("rb") as stream:
            saved = pickle.load(stream)
        assert saved["signature"] == model_signature
        study = saved["study"]
    else:
        study = optuna.create_study(directions=["maximize", "minimize"], sampler=optuna.samplers.NSGAIISampler(seed=seed), study_name=f"readmission_{scheme}_{model_signature}")
        for params in seed_configs:
            study.enqueue_trial(native_params(params))
    if any(trial.state in (optuna.trial.TrialState.FAIL, optuna.trial.TrialState.RUNNING) for trial in study.trials):
        raise RuntimeError("A failed or unfinished trial requires inspection before resuming.")
    def objective(trial):
        params = {}
        for name, (kind, lower, upper, logarithmic) in ranges.items():
            params[name] = trial.suggest_int(name, lower, upper) if kind == "int" else trial.suggest_float(name, lower, upper, log=logarithmic)
        imputation = trial.number % 5 + 1
        trial.set_user_attr("imputation", imputation)
        fold_results = []
        for fold in range(1, 6):
            fold_results.append(evaluate_fold(params, scheme, fold, imputation))
            if len(fold_results) >= minimum_folds and np.mean([row["C"] for row in fold_results]) < minimum_c:
                raise optuna.TrialPruned()
        trial.set_user_attr("global_C", float(np.mean([row["global_C"] for row in fold_results])))
        return float(np.mean([row["C"] for row in fold_results])), float(np.mean([row["mean_Brier"] for row in fold_results]))
    def checkpoint(study, trial):
        save_pickle({"signature": model_signature, "study": study}, study_path)
        print(f"{scheme} trial {trial.number + 1}/{trial_budget}: {trial.state.name}", flush=True)
    finished = sum(trial.state.is_finished() for trial in study.trials)
    if finished > trial_budget:
        raise RuntimeError("Saved study exceeds the fixed trial budget.")
    if finished < trial_budget:
        study.optimize(objective, n_trials=trial_budget - finished, n_jobs=1, callbacks=[checkpoint], show_progress_bar=False)
    assert sum(trial.state.is_finished() for trial in study.trials) == trial_budget
    return study
def rescore_pareto(study, scheme, top_k):
    candidates = pareto_table(study).head(top_k)
    rows, detail = [], {}
    for candidate in candidates.to_dict("records"):
        params = native_params(candidate)
        per_imputation = []
        for imputation in range(1, 6):
            records = [evaluate_fold(params, scheme, fold, imputation) for fold in range(1, 6)]
            per_imputation.append({name: float(np.mean([row[name] for row in records])) for name in ["C", "mean_Brier", "global_C"]})
        trial_id = int(candidate["trial_id"])
        detail[trial_id] = per_imputation
        rows.append({"trial_id": trial_id, **{name: float(np.mean([row[name] for row in per_imputation])) for name in ["C", "mean_Brier", "global_C"]}, "C_SD_across_imputations": float(np.std([row["C"] for row in per_imputation])), "Brier_SD_across_imputations": float(np.std([row["mean_Brier"] for row in per_imputation])), **params})
    table = pd.DataFrame(rows)
    table["Distance_to_Ideal"] = distance_to_ideal(table["C"], table["mean_Brier"])
    table = table.sort_values("Distance_to_Ideal", kind="stable").reset_index(drop=True)
    path = artifact_path(f"xgb_readm_rescored_{scheme}", model_signature, ".pkl")
    save_pickle({"signature": model_signature, "table": table, "detail": detail}, path)
    return table
def informed_seeds(table):
    configs, seen = [], set()
    for row in table.head(7).to_dict("records"):
        params = native_params(row)
        key = json.dumps(params, sort_keys=True)
        if key not in seen:
            configs.append(params)
            seen.add(key)
    return configs
print("Two-objective search functions ready. No study is started in preflight.")
print(f"Elapsed: {(time.perf_counter() - t0) / 60:.3f} minutes")

Two-objective search functions ready. No study is started in preflight.
Elapsed: 0.000 minutes

## Execute the authorized stage
Preflight checks every completed-data CV encoding and writes only the fixed fold manifest. Pilot mode measures one model fit and its scoring using the historical winner; it fits no imputer and supplies no reportable selection result. Full mode executes both new searches and their all-imputation rescoring.
Historical results are comparison references only. Relative to the manuscript workflow, the imputation scope, probabilities, zero-time encoding and initial sampler reproducibility changed together; their separate contributions cannot be inferred from the aggregate comparison.

In [12]:
#| label: readm-run-authorized-stage
#| message: false
t0 = time.perf_counter()
# Execute only the compute stage selected after the user's resource decision.
pilot_result, initial_table, final_table = None, None, None
if mode == "preflight":
    # Check every actual fold/imputation encoding before authorizing expensive model fits.
    encoding_audit = []
    for imputation in range(1, 6):
        for scheme in splits:
            for fold in range(1, 6):
                x_train, x_valid, y_train, y_valid, metadata = encoded_fold(scheme, fold, imputation)
                assert len(x_train) + len(x_valid) == len(development_data)
                assert not set(metadata_names + outcome_names).intersection(x_train.columns)
                encoding_audit.append({"Imputation": imputation, "Scheme": scheme, "Fold": fold, "Encoded predictors": x_train.shape[1], "Missing training": int(x_train.isna().sum().sum()), "Missing validation": int(x_valid.isna().sum().sum())})
    show_table(pd.DataFrame(encoding_audit), "All completed-data CV encodings verified without model fitting")
    del x_train, x_valid, y_train, y_valid, metadata
    print("Preflight passed. No imputer, XGBoost model or Optuna trial was fitted.")
elif mode == "pilot":
    pilot_result = evaluate_fold(native_params(historical_winner), "plan", 1, 1)
    show_table(pd.DataFrame({"Item": ["Purpose", "New imputation fits", "Model fitting time (minutes)", "Model plus scoring time (minutes)", "Returned boosting rounds", "Best iteration", "Encoded predictors"], "Value": ["Timing only; not reportable", 0, pilot_result["fit_seconds"] / 60, pilot_result["model_and_scoring_seconds"] / 60, pilot_result["returned_rounds"], pilot_result["best_iteration"], len(pilot_result["features"])]}), "Single-fold timing pilot")
else:
    initial_study = optimize_stage("plan", 100)
    show_table(pareto_table(initial_study), "Initial Pareto candidates, one imputation per trial")
    initial_table = rescore_pareto(initial_study, "plan", 20)
    show_table(initial_table, "Initial candidates rescored on all five imputations")
    refined_study = optimize_stage("dual", 50, informed_seeds(initial_table))
    show_table(pareto_table(refined_study), "Informed Pareto candidates, one imputation per trial")
    final_table = rescore_pareto(refined_study, "dual", 10)
    show_table(final_table, "Final candidates rescored on all five imputations")
print(f"Elapsed: {(time.perf_counter() - t0) / 60:.3f} minutes")

[I 2026-10-03 12:42:36,461] A new study created in memory with name: readmission_plan_f53816455a8a

[I 2026-10-03 12:43:25,987] Trial 0 finished with values: [0.6457070806524315, 0.10946563111746768] and parameters: {'learning_rate': 0.0038280102753304847, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6395345367575241, 'colsample_bytree': 0.6442393742200758, 'reg_alpha': 0.1436757127036174, 'reg_lambda': 0.7578459397323387, 'gamma': 0.0829340446620956}.

plan trial 1/100: COMPLETE

[I 2026-10-03 12:44:05,283] Trial 1 finished with values: [0.6449645858055539, 0.1095862755102833] and parameters: {'learning_rate': 0.008582013741066118, 'max_depth': 9, 'min_child_weight': 25, 'subsample': 0.723327121538445, 'colsample_bytree': 0.5644318856745857, 'reg_alpha': 0.8237691529375192, 'reg_lambda': 3.1720500897865564, 'gamma': 0.2295819372628562}.

plan trial 2/100: COMPLETE

[I 2026-10-03 12:44:50,749] Trial 2 finished with values: [0.6458849236019472, 0.10947903032145243] and parameters: {'learning_rate': 0.007232394882074714, 'max_depth': 7, 'min_child_weight': 24, 'subsample': 0.7220163970989083, 'colsample_bytree': 0.6153422043987612, 'reg_alpha': 0.0041137106950810765, 'reg_lambda': 0.21223891856500232, 'gamma': 0.18114525808024567}.

plan trial 3/100: COMPLETE

[I 2026-10-03 12:45:46,861] Trial 3 finished with values: [0.6457370878816603, 0.10945074109155088] and parameters: {'learning_rate': 0.004910136343876599, 'max_depth': 8, 'min_child_weight': 20, 'subsample': 0.8202280631532665, 'colsample_bytree': 0.43208947692495325, 'reg_alpha': 0.4286906704972381, 'reg_lambda': 3.4037233990143423, 'gamma': 0.26995438263879673}.

plan trial 4/100: COMPLETE

[I 2026-10-03 12:46:22,071] Trial 4 finished with values: [0.6446758506657331, 0.10956340592159333] and parameters: {'learning_rate': 0.01098610678602083, 'max_depth': 9, 'min_child_weight': 28, 'subsample': 0.6250502548265082, 'colsample_bytree': 0.6455812619950292, 'reg_alpha': 0.009750263994785456, 'reg_lambda': 8.45881561160167, 'gamma': 0.24055921823901244}.

plan trial 5/100: COMPLETE

[I 2026-10-03 12:46:47,543] Trial 5 finished with values: [0.6429589095684962, 0.10976758994351062] and parameters: {'learning_rate': 0.03373795017369714, 'max_depth': 9, 'min_child_weight': 26, 'subsample': 0.6539471440558556, 'colsample_bytree': 0.6762389078193798, 'reg_alpha': 0.0018247131502634882, 'reg_lambda': 0.9330755988606588, 'gamma': 0.5292581216124667}.

plan trial 6/100: COMPLETE

[I 2026-10-03 12:47:45,281] Trial 6 finished with values: [0.6465778052172813, 0.10947439277459625] and parameters: {'learning_rate': 0.00374941216715763, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.8044197687853442, 'colsample_bytree': 0.47066387888986894, 'reg_alpha': 0.580114334811206, 'reg_lambda': 0.2910669822868854, 'gamma': 1.1548161000679031}.

plan trial 7/100: COMPLETE

[I 2026-10-03 12:48:40,121] Trial 7 finished with values: [0.6464982721003295, 0.1095177842718948] and parameters: {'learning_rate': 0.003937534064623471, 'max_depth': 9, 'min_child_weight': 5, 'subsample': 0.8272160609666579, 'colsample_bytree': 0.46849666338795903, 'reg_alpha': 0.0012689920611310094, 'reg_lambda': 0.12594597985355963, 'gamma': 0.03636309175058783}.

plan trial 8/100: COMPLETE

[I 2026-10-03 12:49:12,938] Trial 8 finished with values: [0.6452706780139984, 0.10943840993420444] and parameters: {'learning_rate': 0.012133145372404076, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.8972903510269807, 'colsample_bytree': 0.5193064189048473, 'reg_alpha': 0.0398615832269852, 'reg_lambda': 1.1840859322116128, 'gamma': 0.46512564796488876}.

plan trial 9/100: COMPLETE

[I 2026-10-03 12:49:44,519] Trial 9 finished with values: [0.6460072043691076, 0.10947690483945072] and parameters: {'learning_rate': 0.012557117251127542, 'max_depth': 6, 'min_child_weight': 15, 'subsample': 0.8700493020711223, 'colsample_bytree': 0.5917310550205028, 'reg_alpha': 0.011226361553524824, 'reg_lambda': 2.90599001745992, 'gamma': 0.09865512817314494}.

plan trial 10/100: COMPLETE

[I 2026-10-03 12:50:31,564] Trial 10 finished with values: [0.6443136096206996, 0.10943250469396107] and parameters: {'learning_rate': 0.005143873480065005, 'max_depth': 6, 'min_child_weight': 29, 'subsample': 0.6160102180836932, 'colsample_bytree': 0.5121326688388974, 'reg_alpha': 1.146901994328003, 'reg_lambda': 5.0641057870681285, 'gamma': 1.0680306831128887}.

plan trial 11/100: COMPLETE

[I 2026-10-03 12:50:50,973] Trial 11 finished with values: [0.6453870568782157, 0.1095688753841024] and parameters: {'learning_rate': 0.022260728588262314, 'max_depth': 7, 'min_child_weight': 5, 'subsample': 0.8632124602448938, 'colsample_bytree': 0.4763936303773111, 'reg_alpha': 0.12147565642073768, 'reg_lambda': 0.365593326596524, 'gamma': 0.058101306745059283}.

plan trial 12/100: COMPLETE

[I 2026-10-03 12:51:40,440] Trial 12 finished with values: [0.6451543021316173, 0.10940701413490694] and parameters: {'learning_rate': 0.005334675708807413, 'max_depth': 6, 'min_child_weight': 18, 'subsample': 0.8431922964240449, 'colsample_bytree': 0.5647847323242832, 'reg_alpha': 0.08127020211966773, 'reg_lambda': 3.7289782908955407, 'gamma': 0.05972495456565448}.

plan trial 13/100: COMPLETE

[I 2026-10-03 12:52:12,477] Trial 13 finished with values: [0.6452892402384286, 0.1094182167570179] and parameters: {'learning_rate': 0.01689423858576688, 'max_depth': 4, 'min_child_weight': 11, 'subsample': 0.886097910041558, 'colsample_bytree': 0.4343454392497529, 'reg_alpha': 0.15079174647147364, 'reg_lambda': 0.4254455661099687, 'gamma': 0.039541210999596975}.

plan trial 14/100: COMPLETE

[I 2026-10-03 12:52:35,117] Trial 14 finished with values: [0.645412012918493, 0.1095134228680474] and parameters: {'learning_rate': 0.017605714927279803, 'max_depth': 7, 'min_child_weight': 26, 'subsample': 0.6783588190263752, 'colsample_bytree': 0.6675350883103686, 'reg_alpha': 0.00572380548021796, 'reg_lambda': 1.9682101437034563, 'gamma': 0.014692798156764731}.

plan trial 15/100: COMPLETE

[I 2026-10-03 12:53:26,657] Trial 15 finished with values: [0.6451868242222913, 0.10939082258038782] and parameters: {'learning_rate': 0.004546778099081987, 'max_depth': 6, 'min_child_weight': 8, 'subsample': 0.6860574649730077, 'colsample_bytree': 0.5605756204671131, 'reg_alpha': 0.24105770387322079, 'reg_lambda': 0.8599233219375855, 'gamma': 0.7311574585915983}.

plan trial 16/100: COMPLETE

[I 2026-10-03 12:54:02,758] Trial 16 finished with values: [0.6455732845133016, 0.10951538274926242] and parameters: {'learning_rate': 0.010937714520447854, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.7055033715767773, 'colsample_bytree': 0.6734372126436267, 'reg_alpha': 0.07629571491433539, 'reg_lambda': 9.029336586148995, 'gamma': 1.1197596296673287}.

plan trial 17/100: COMPLETE

[I 2026-10-03 12:54:23,103] Trial 17 finished with values: [0.6441007241974382, 0.10954500110012899] and parameters: {'learning_rate': 0.031589800526477585, 'max_depth': 6, 'min_child_weight': 14, 'subsample': 0.6271475096396126, 'colsample_bytree': 0.4084819027767599, 'reg_alpha': 0.22783432125308814, 'reg_lambda': 2.5091735621147517, 'gamma': 0.15262401810355875}.

plan trial 18/100: COMPLETE

[I 2026-10-03 12:55:05,776] Trial 18 finished with values: [0.6464996702177203, 0.109511650321057] and parameters: {'learning_rate': 0.006482473196621928, 'max_depth': 9, 'min_child_weight': 10, 'subsample': 0.8616045805437124, 'colsample_bytree': 0.4101445810148692, 'reg_alpha': 0.021662321786466297, 'reg_lambda': 1.0394751471340036, 'gamma': 0.7381804070309487}.

plan trial 19/100: COMPLETE

[I 2026-10-03 12:55:43,440] Trial 19 finished with values: [0.6454276034756349, 0.10943573894482776] and parameters: {'learning_rate': 0.012711880483356074, 'max_depth': 5, 'min_child_weight': 28, 'subsample': 0.736838848424201, 'colsample_bytree': 0.591959311487665, 'reg_alpha': 0.004476668910418181, 'reg_lambda': 1.0058477165353126, 'gamma': 0.05453945795646964}.

plan trial 20/100: COMPLETE

[I 2026-10-03 12:56:43,585] Trial 20 finished with values: [0.6457188974438168, 0.10948718244564212] and parameters: {'learning_rate': 0.0042721879589528, 'max_depth': 9, 'min_child_weight': 15, 'subsample': 0.6192556002153113, 'colsample_bytree': 0.42864318009804186, 'reg_alpha': 0.34786969074571267, 'reg_lambda': 1.163792213611752, 'gamma': 0.05304297368583254}.

plan trial 21/100: COMPLETE

[I 2026-10-03 12:57:23,113] Trial 21 finished with values: [0.6453537830679682, 0.10950252190690364] and parameters: {'learning_rate': 0.009210528250708458, 'max_depth': 7, 'min_child_weight': 30, 'subsample': 0.8498679787316155, 'colsample_bytree': 0.5752660923362173, 'reg_alpha': 0.03398887654631574, 'reg_lambda': 2.281631905188626, 'gamma': 0.027885469437387338}.

plan trial 22/100: COMPLETE

[I 2026-10-03 12:58:26,699] Trial 22 finished with values: [0.6459693870017074, 0.10943285406271688] and parameters: {'learning_rate': 0.005517994026635822, 'max_depth': 7, 'min_child_weight': 16, 'subsample': 0.8685164626832975, 'colsample_bytree': 0.5518483265305354, 'reg_alpha': 0.0031717388086982354, 'reg_lambda': 1.1677480956814825, 'gamma': 0.024220049272347582}.

plan trial 23/100: COMPLETE

[I 2026-10-03 12:58:45,987] Trial 23 finished with values: [0.6444091969701307, 0.10956957737656677] and parameters: {'learning_rate': 0.028716118344426382, 'max_depth': 7, 'min_child_weight': 16, 'subsample': 0.6057237552347768, 'colsample_bytree': 0.48192065736323153, 'reg_alpha': 0.036867086660385635, 'reg_lambda': 1.0657677750195418, 'gamma': 0.010882240854042506}.

plan trial 24/100: COMPLETE

[I 2026-10-03 12:59:36,536] Trial 24 finished with values: [0.6440262105411689, 0.10941151984847206] and parameters: {'learning_rate': 0.004370881039092839, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7163206293939532, 'colsample_bytree': 0.5932035485965139, 'reg_alpha': 0.006702658164071285, 'reg_lambda': 0.4466285489787785, 'gamma': 0.023853751233972403}.

plan trial 25/100: COMPLETE

[I 2026-10-03 13:00:03,342] Trial 25 finished with values: [0.6457215558329009, 0.10945850258733532] and parameters: {'learning_rate': 0.023985139569256908, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.7235627542430807, 'colsample_bytree': 0.662670111614476, 'reg_alpha': 0.01047886223833977, 'reg_lambda': 0.21644033624761616, 'gamma': 0.42047891028099316}.

plan trial 26/100: COMPLETE

[I 2026-10-03 13:00:56,788] Trial 26 finished with values: [0.6461005941877325, 0.10942848084165632] and parameters: {'learning_rate': 0.006448095286130664, 'max_depth': 6, 'min_child_weight': 18, 'subsample': 0.8174123383615022, 'colsample_bytree': 0.6618201400344565, 'reg_alpha': 0.04146144961745777, 'reg_lambda': 1.9293808078661845, 'gamma': 0.027380145272973933}.

plan trial 27/100: COMPLETE

[I 2026-10-03 13:01:45,654] Trial 27 finished with values: [0.6405861623267919, 0.10946314561132338] and parameters: {'learning_rate': 0.00264971710051582, 'max_depth': 5, 'min_child_weight': 16, 'subsample': 0.8111651647710512, 'colsample_bytree': 0.5766841506253431, 'reg_alpha': 0.001307356307358973, 'reg_lambda': 0.8763161972016067, 'gamma': 0.07417560761248457}.

plan trial 28/100: COMPLETE

[I 2026-10-03 13:02:33,024] Trial 28 finished with values: [0.6423021890904863, 0.10948910530575498] and parameters: {'learning_rate': 0.006743424000392561, 'max_depth': 4, 'min_child_weight': 30, 'subsample': 0.7615298075660988, 'colsample_bytree': 0.4899940858488727, 'reg_alpha': 0.03318640370815431, 'reg_lambda': 5.00047958454814, 'gamma': 1.171780270352262}.

plan trial 29/100: COMPLETE

[I 2026-10-03 13:03:21,986] Trial 29 finished with values: [0.6444199812056919, 0.10941999021028057] and parameters: {'learning_rate': 0.005747156882761925, 'max_depth': 5, 'min_child_weight': 25, 'subsample': 0.7084857940695516, 'colsample_bytree': 0.5925657645986632, 'reg_alpha': 0.6480511316545403, 'reg_lambda': 1.5388987635272628, 'gamma': 0.023124633180514446}.

plan trial 30/100: COMPLETE

[I 2026-10-03 13:04:15,833] Trial 30 finished with values: [0.6425929940532032, 0.10941473225270251] and parameters: {'learning_rate': 0.0033205331356144312, 'max_depth': 6, 'min_child_weight': 27, 'subsample': 0.8825930948689846, 'colsample_bytree': 0.5557801568951307, 'reg_alpha': 0.2538341872100312, 'reg_lambda': 0.39607348580681334, 'gamma': 0.02898952815994795}.

plan trial 31/100: COMPLETE

[I 2026-10-03 13:05:05,371] Trial 31 finished with values: [0.646347875119268, 0.10949861125192792] and parameters: {'learning_rate': 0.006120014041941562, 'max_depth': 8, 'min_child_weight': 12, 'subsample': 0.8347795720230198, 'colsample_bytree': 0.47696764713162626, 'reg_alpha': 0.16690880124896543, 'reg_lambda': 6.320973072349098, 'gamma': 0.741152998880233}.

plan trial 32/100: COMPLETE

[I 2026-10-03 13:05:24,975] Trial 32 finished with values: [0.644984633141316, 0.10967837714567956] and parameters: {'learning_rate': 0.0262819126381573, 'max_depth': 9, 'min_child_weight': 12, 'subsample': 0.8479598043493827, 'colsample_bytree': 0.5200435467260067, 'reg_alpha': 0.045395681857058966, 'reg_lambda': 8.716538801681102, 'gamma': 0.01133896463402866}.

plan trial 33/100: COMPLETE

[I 2026-10-03 13:06:12,567] Trial 33 finished with values: [0.6454626954954714, 0.10943745203578834] and parameters: {'learning_rate': 0.00615303074234933, 'max_depth': 7, 'min_child_weight': 28, 'subsample': 0.7532278886361137, 'colsample_bytree': 0.5007216146480863, 'reg_alpha': 0.18888780864812524, 'reg_lambda': 0.1730751925512587, 'gamma': 0.026560847322503172}.

plan trial 34/100: COMPLETE

[I 2026-10-03 13:07:03,393] Trial 34 finished with values: [0.6456025060426466, 0.10949995581056804] and parameters: {'learning_rate': 0.004570799882103182, 'max_depth': 9, 'min_child_weight': 17, 'subsample': 0.7284474672852912, 'colsample_bytree': 0.6555765515825789, 'reg_alpha': 0.2027066421529147, 'reg_lambda': 0.13582845224617948, 'gamma': 0.0639609916004247}.

plan trial 35/100: COMPLETE

[I 2026-10-03 13:07:41,270] Trial 35 finished with values: [0.6455736188989254, 0.10940910944469666] and parameters: {'learning_rate': 0.007338959702060606, 'max_depth': 7, 'min_child_weight': 14, 'subsample': 0.640377410333114, 'colsample_bytree': 0.6098723940364368, 'reg_alpha': 0.1582319870715591, 'reg_lambda': 0.7412576614964576, 'gamma': 0.02749774642137288}.

plan trial 36/100: COMPLETE

[I 2026-10-03 13:08:30,199] Trial 36 finished with values: [0.6451733727251381, 0.10944674539913199] and parameters: {'learning_rate': 0.005916084379289415, 'max_depth': 6, 'min_child_weight': 29, 'subsample': 0.7956833104492665, 'colsample_bytree': 0.6753866781557616, 'reg_alpha': 0.43264790229504013, 'reg_lambda': 0.35135126499321806, 'gamma': 0.5412033937468453}.

plan trial 37/100: COMPLETE

[I 2026-10-03 13:09:26,388] Trial 37 finished with values: [0.6450931052998199, 0.10945879954173876] and parameters: {'learning_rate': 0.004081741982364131, 'max_depth': 8, 'min_child_weight': 23, 'subsample': 0.7459727184045157, 'colsample_bytree': 0.5533417480792635, 'reg_alpha': 0.03515757566995316, 'reg_lambda': 0.14586776668058257, 'gamma': 1.0900675832477493}.

plan trial 38/100: COMPLETE

[I 2026-10-03 13:10:00,153] Trial 38 finished with values: [0.6457494140396344, 0.10952100640108405] and parameters: {'learning_rate': 0.007531770129745854, 'max_depth': 9, 'min_child_weight': 12, 'subsample': 0.6833292658612521, 'colsample_bytree': 0.6296339045531486, 'reg_alpha': 0.005611261679255503, 'reg_lambda': 0.7568952344128784, 'gamma': 0.9998155545806454}.

plan trial 39/100: COMPLETE

[I 2026-10-03 13:10:45,550] Trial 39 finished with values: [0.6457230348473163, 0.10938978373226846] and parameters: {'learning_rate': 0.006731222648259909, 'max_depth': 5, 'min_child_weight': 5, 'subsample': 0.7139277498525687, 'colsample_bytree': 0.4977613276410141, 'reg_alpha': 0.2961438123248616, 'reg_lambda': 2.634563107932524, 'gamma': 0.18709665744346862}.

plan trial 40/100: COMPLETE

[I 2026-10-03 13:11:54,061] Trial 40 finished with values: [0.6429617595098833, 0.10945482691796977] and parameters: {'learning_rate': 0.002073544184493735, 'max_depth': 9, 'min_child_weight': 30, 'subsample': 0.6238446412853621, 'colsample_bytree': 0.5626364285519182, 'reg_alpha': 0.01857649561071943, 'reg_lambda': 0.7189504700879056, 'gamma': 0.013096926489868713}.

plan trial 41/100: COMPLETE

[I 2026-10-03 13:12:53,995] Trial 41 finished with values: [0.6431502374907667, 0.10941753947868105] and parameters: {'learning_rate': 0.0021463191070240253, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7797398007531671, 'colsample_bytree': 0.5108916580638999, 'reg_alpha': 0.03597771364480829, 'reg_lambda': 1.5306598728411798, 'gamma': 0.029272707397306877}.

plan trial 42/100: COMPLETE

[I 2026-10-03 13:13:21,153] Trial 42 finished with values: [0.6457298055849459, 0.10954165413707465] and parameters: {'learning_rate': 0.01243386731799552, 'max_depth': 9, 'min_child_weight': 10, 'subsample': 0.627647032110041, 'colsample_bytree': 0.46757894269245187, 'reg_alpha': 0.002257339442000069, 'reg_lambda': 0.20756284766202893, 'gamma': 0.47277643428302907}.

plan trial 43/100: COMPLETE

[I 2026-10-03 13:13:45,341] Trial 43 finished with values: [0.6445478541119908, 0.10941951491679106] and parameters: {'learning_rate': 0.025241870010966096, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.6797473508749233, 'colsample_bytree': 0.545662122162508, 'reg_alpha': 0.001625981005371854, 'reg_lambda': 0.4814236511461741, 'gamma': 0.10370879387942096}.

plan trial 44/100: COMPLETE

[I 2026-10-03 13:14:04,815] Trial 44 finished with values: [0.6452099015534112, 0.10956030039409992] and parameters: {'learning_rate': 0.03289455923292345, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.6472037030847235, 'colsample_bytree': 0.6238477236308952, 'reg_alpha': 0.117730182396369, 'reg_lambda': 4.998791247324388, 'gamma': 0.03600516015897879}.

plan trial 45/100: COMPLETE

[I 2026-10-03 13:14:24,344] Trial 45 finished with values: [0.6444244262169532, 0.10959150834203293] and parameters: {'learning_rate': 0.020629979041758558, 'max_depth': 9, 'min_child_weight': 25, 'subsample': 0.7922670135794455, 'colsample_bytree': 0.5142033884974042, 'reg_alpha': 0.03276885292053393, 'reg_lambda': 0.13478369391641765, 'gamma': 0.23020467407008977}.

plan trial 46/100: COMPLETE

[I 2026-10-03 13:15:01,839] Trial 46 finished with values: [0.6462448509372829, 0.10945302881858683] and parameters: {'learning_rate': 0.007997647198861969, 'max_depth': 6, 'min_child_weight': 14, 'subsample': 0.8262393174195208, 'colsample_bytree': 0.5881139673827626, 'reg_alpha': 0.6796212610997706, 'reg_lambda': 2.1640968670323524, 'gamma': 1.2226437840194744}.

plan trial 47/100: COMPLETE

[I 2026-10-03 13:15:41,154] Trial 47 finished with values: [0.6424264582094709, 0.10947071425795687] and parameters: {'learning_rate': 0.0062459550224895, 'max_depth': 4, 'min_child_weight': 29, 'subsample': 0.7206718877186021, 'colsample_bytree': 0.6793020307972057, 'reg_alpha': 0.015101927098715837, 'reg_lambda': 5.52174736051065, 'gamma': 0.12856626346725913}.

plan trial 48/100: COMPLETE

[I 2026-10-03 13:16:15,450] Trial 48 finished with values: [0.6454789845892546, 0.10942630814051138] and parameters: {'learning_rate': 0.011535898701146796, 'max_depth': 5, 'min_child_weight': 27, 'subsample': 0.6268441052486139, 'colsample_bytree': 0.6098863810145034, 'reg_alpha': 0.2545972459806758, 'reg_lambda': 0.2709945927369134, 'gamma': 0.08802822232922433}.

plan trial 49/100: COMPLETE

[I 2026-10-03 13:16:46,066] Trial 49 finished with values: [0.6465031723369574, 0.10940542627351509] and parameters: {'learning_rate': 0.012839666035174722, 'max_depth': 5, 'min_child_weight': 7, 'subsample': 0.7302000895830555, 'colsample_bytree': 0.48931362707095033, 'reg_alpha': 0.009259257365774149, 'reg_lambda': 0.13143853758621094, 'gamma': 0.02513195844549469}.

plan trial 50/100: COMPLETE

[I 2026-10-03 13:17:45,987] Trial 50 finished with values: [0.6470736205918364, 0.10947048968656423] and parameters: {'learning_rate': 0.003937534064623471, 'max_depth': 9, 'min_child_weight': 10, 'subsample': 0.8272160609666579, 'colsample_bytree': 0.4101445810148692, 'reg_alpha': 0.0012689920611310094, 'reg_lambda': 0.12594597985355963, 'gamma': 0.03636309175058783}.

plan trial 51/100: COMPLETE

[I 2026-10-03 13:18:39,515] Trial 51 finished with values: [0.646566328543092, 0.10956034256351643] and parameters: {'learning_rate': 0.004370881039092839, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7163206293939532, 'colsample_bytree': 0.6442393742200758, 'reg_alpha': 0.006702658164071285, 'reg_lambda': 0.4466285489787785, 'gamma': 0.023853751233972403}.

plan trial 52/100: COMPLETE

[I 2026-10-03 13:19:29,748] Trial 52 finished with values: [0.6455036807911296, 0.10953630935094409] and parameters: {'learning_rate': 0.005517994026635822, 'max_depth': 9, 'min_child_weight': 16, 'subsample': 0.8685164626832975, 'colsample_bytree': 0.5518483265305354, 'reg_alpha': 0.0031717388086982354, 'reg_lambda': 1.1677480956814825, 'gamma': 0.024220049272347582}.

plan trial 53/100: COMPLETE

[I 2026-10-03 13:20:21,489] Trial 53 finished with values: [0.6461646333479001, 0.10956653482891829] and parameters: {'learning_rate': 0.006731222648259909, 'max_depth': 9, 'min_child_weight': 5, 'subsample': 0.7922670135794455, 'colsample_bytree': 0.4375599579503726, 'reg_alpha': 0.03276885292053393, 'reg_lambda': 2.634563107932524, 'gamma': 0.454211574910779}.

plan trial 54/100: COMPLETE

[I 2026-10-03 13:20:51,738] Trial 54 finished with values: [0.6451903908453295, 0.10961410483407275] and parameters: {'learning_rate': 0.014936981587627043, 'max_depth': 9, 'min_child_weight': 15, 'subsample': 0.8632124602448938, 'colsample_bytree': 0.4763936303773111, 'reg_alpha': 0.12147565642073768, 'reg_lambda': 1.163792213611752, 'gamma': 0.058101306745059283}.

plan trial 55/100: COMPLETE

[I 2026-10-03 13:21:38,389] Trial 55 finished with values: [0.644270285649063, 0.10940613526941696] and parameters: {'learning_rate': 0.007531770129745854, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.7235627542430807, 'colsample_bytree': 0.662670111614476, 'reg_alpha': 0.01047886223833977, 'reg_lambda': 0.7568952344128784, 'gamma': 0.9998155545806454}.

plan trial 56/100: COMPLETE

[I 2026-10-03 13:22:22,090] Trial 56 finished with values: [0.6458935498991798, 0.10952278362299772] and parameters: {'learning_rate': 0.008206899891651962, 'max_depth': 9, 'min_child_weight': 16, 'subsample': 0.8685164626832975, 'colsample_bytree': 0.4101445810148692, 'reg_alpha': 0.021662321786466297, 'reg_lambda': 1.0394751471340036, 'gamma': 0.024220049272347582}.

plan trial 57/100: COMPLETE

[I 2026-10-03 13:22:49,665] Trial 57 finished with values: [0.6452740422525681, 0.10964782693428927] and parameters: {'learning_rate': 0.01689423858576688, 'max_depth': 8, 'min_child_weight': 11, 'subsample': 0.8528069808529624, 'colsample_bytree': 0.6745254191359105, 'reg_alpha': 0.15079174647147364, 'reg_lambda': 0.14586776668058257, 'gamma': 0.039541210999596975}.

plan trial 58/100: COMPLETE

[I 2026-10-03 13:23:26,174] Trial 58 finished with values: [0.6459631206300719, 0.10950180421920655] and parameters: {'learning_rate': 0.01243386731799552, 'max_depth': 7, 'min_child_weight': 10, 'subsample': 0.627647032110041, 'colsample_bytree': 0.46757894269245187, 'reg_alpha': 0.002257339442000069, 'reg_lambda': 7.4268768487906, 'gamma': 0.47277643428302907}.

plan trial 59/100: COMPLETE

[I 2026-10-03 13:24:16,249] Trial 59 finished with values: [0.6458289250815691, 0.10955883861346234] and parameters: {'learning_rate': 0.0062459550224895, 'max_depth': 9, 'min_child_weight': 10, 'subsample': 0.7206718877186021, 'colsample_bytree': 0.6793020307972057, 'reg_alpha': 0.021662321786466297, 'reg_lambda': 0.24531974243053864, 'gamma': 0.12856626346725913}.

plan trial 60/100: COMPLETE

[I 2026-10-03 13:25:09,312] Trial 60 finished with values: [0.6464845480274818, 0.10941990395748505] and parameters: {'learning_rate': 0.007531770129745854, 'max_depth': 6, 'min_child_weight': 12, 'subsample': 0.6833292658612521, 'colsample_bytree': 0.46849666338795903, 'reg_alpha': 0.005611261679255503, 'reg_lambda': 0.12594597985355963, 'gamma': 0.9998155545806454}.

plan trial 61/100: COMPLETE

[I 2026-10-03 13:26:10,999] Trial 61 finished with values: [0.6450087191055044, 0.10940751829682764] and parameters: {'learning_rate': 0.00374941216715763, 'max_depth': 7, 'min_child_weight': 16, 'subsample': 0.6477872401219568, 'colsample_bytree': 0.6153422043987612, 'reg_alpha': 0.0041137106950810765, 'reg_lambda': 0.21223891856500232, 'gamma': 1.1548161000679031}.

plan trial 62/100: COMPLETE

[I 2026-10-03 13:26:54,680] Trial 62 finished with values: [0.6464788711962015, 0.10945269750005157] and parameters: {'learning_rate': 0.007232394882074714, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6395345367575241, 'colsample_bytree': 0.6153422043987612, 'reg_alpha': 0.0041137106950810765, 'reg_lambda': 0.7578459397323387, 'gamma': 0.18114525808024567}.

plan trial 63/100: COMPLETE

[I 2026-10-03 13:27:28,940] Trial 63 finished with values: [0.644663270434564, 0.10945097072840755] and parameters: {'learning_rate': 0.012557117251127542, 'max_depth': 6, 'min_child_weight': 27, 'subsample': 0.8700493020711223, 'colsample_bytree': 0.5557801568951307, 'reg_alpha': 0.2538341872100312, 'reg_lambda': 2.90599001745992, 'gamma': 0.09865512817314494}.

plan trial 64/100: COMPLETE

[I 2026-10-03 13:27:56,644] Trial 64 finished with values: [0.6451164686292171, 0.10946827175623927] and parameters: {'learning_rate': 0.023985139569256908, 'max_depth': 4, 'min_child_weight': 29, 'subsample': 0.7235627542430807, 'colsample_bytree': 0.662670111614476, 'reg_alpha': 0.01047886223833977, 'reg_lambda': 0.21644033624761616, 'gamma': 0.42047891028099316}.

plan trial 65/100: COMPLETE

[I 2026-10-03 13:28:43,459] Trial 65 finished with values: [0.6461890956067697, 0.10945925151966729] and parameters: {'learning_rate': 0.006731222648259909, 'max_depth': 7, 'min_child_weight': 5, 'subsample': 0.7139277498525687, 'colsample_bytree': 0.6153422043987612, 'reg_alpha': 0.2961438123248616, 'reg_lambda': 3.1913407653184565, 'gamma': 0.18114525808024567}.

plan trial 66/100: COMPLETE

[I 2026-10-03 13:29:42,455] Trial 66 finished with values: [0.6450938865855029, 0.10945042089570764] and parameters: {'learning_rate': 0.005916084379289415, 'max_depth': 6, 'min_child_weight': 29, 'subsample': 0.7956833104492665, 'colsample_bytree': 0.6649808945670337, 'reg_alpha': 0.43264790229504013, 'reg_lambda': 0.21644033624761616, 'gamma': 0.5412033937468453}.

plan trial 67/100: COMPLETE

[I 2026-10-03 13:30:31,249] Trial 67 finished with values: [0.638696236019386, 0.10955342664900877] and parameters: {'learning_rate': 0.002773278835799442, 'max_depth': 4, 'min_child_weight': 12, 'subsample': 0.8347795720230198, 'colsample_bytree': 0.47696764713162626, 'reg_alpha': 0.055789979543060836, 'reg_lambda': 0.365593326596524, 'gamma': 0.741152998880233}.

plan trial 68/100: COMPLETE

[I 2026-10-03 13:31:10,939] Trial 68 finished with values: [0.6447286989389925, 0.10953387834770296] and parameters: {'learning_rate': 0.007531770129745854, 'max_depth': 9, 'min_child_weight': 12, 'subsample': 0.8700493020711223, 'colsample_bytree': 0.5917310550205028, 'reg_alpha': 0.2596476774716138, 'reg_lambda': 0.7568952344128784, 'gamma': 1.4158757092528182}.

plan trial 69/100: COMPLETE

[I 2026-10-03 13:32:13,876] Trial 69 finished with values: [0.6455380831551815, 0.10939209946134014] and parameters: {'learning_rate': 0.004546778099081987, 'max_depth': 6, 'min_child_weight': 8, 'subsample': 0.6820669948424662, 'colsample_bytree': 0.5605756204671131, 'reg_alpha': 0.24105770387322079, 'reg_lambda': 0.8599233219375855, 'gamma': 0.051294174716689685}.

plan trial 70/100: COMPLETE

[I 2026-10-03 13:32:59,313] Trial 70 finished with values: [0.6463923098484468, 0.10941395417259933] and parameters: {'learning_rate': 0.006448095286130664, 'max_depth': 7, 'min_child_weight': 9, 'subsample': 0.8174123383615022, 'colsample_bytree': 0.6153422043987612, 'reg_alpha': 0.0041137106950810765, 'reg_lambda': 1.9293808078661845, 'gamma': 0.18114525808024567}.

plan trial 71/100: COMPLETE

[I 2026-10-03 13:33:35,142] Trial 71 finished with values: [0.6452593833387678, 0.10950702616909977] and parameters: {'learning_rate': 0.007997647198861969, 'max_depth': 7, 'min_child_weight': 14, 'subsample': 0.6783588190263752, 'colsample_bytree': 0.5881139673827626, 'reg_alpha': 0.6796212610997706, 'reg_lambda': 7.508848761427604, 'gamma': 0.014692798156764731}.

plan trial 72/100: COMPLETE

[I 2026-10-03 13:34:18,470] Trial 72 finished with values: [0.6456541965988274, 0.10944494229220023] and parameters: {'learning_rate': 0.005517994026635822, 'max_depth': 7, 'min_child_weight': 26, 'subsample': 0.8498679787316155, 'colsample_bytree': 0.5752660923362173, 'reg_alpha': 0.03398887654631574, 'reg_lambda': 2.281631905188626, 'gamma': 0.024220049272347582}.

plan trial 73/100: COMPLETE

[I 2026-10-03 13:34:46,458] Trial 73 finished with values: [0.6446480243952001, 0.1094632117224508] and parameters: {'learning_rate': 0.012711880483356074, 'max_depth': 5, 'min_child_weight': 28, 'subsample': 0.736838848424201, 'colsample_bytree': 0.6813256548545741, 'reg_alpha': 0.004476668910418181, 'reg_lambda': 1.0058477165353126, 'gamma': 0.037874607505845134}.

plan trial 74/100: COMPLETE

[I 2026-10-03 13:35:30,093] Trial 74 finished with values: [0.6460955279259277, 0.109430986236481] and parameters: {'learning_rate': 0.005517994026635822, 'max_depth': 7, 'min_child_weight': 16, 'subsample': 0.8685164626832975, 'colsample_bytree': 0.5108916580638999, 'reg_alpha': 0.6083610523660073, 'reg_lambda': 1.1677480956814825, 'gamma': 0.024220049272347582}.

plan trial 75/100: COMPLETE

[I 2026-10-03 13:36:09,575] Trial 75 finished with values: [0.6451197951422116, 0.1094002832619573] and parameters: {'learning_rate': 0.007098265180048249, 'max_depth': 5, 'min_child_weight': 28, 'subsample': 0.6268441052486139, 'colsample_bytree': 0.591959311487665, 'reg_alpha': 0.01832841185862831, 'reg_lambda': 0.2709945927369134, 'gamma': 0.05453945795646964}.

plan trial 76/100: COMPLETE

[I 2026-10-03 13:36:32,172] Trial 76 finished with values: [0.6451514966682556, 0.10958284778168106] and parameters: {'learning_rate': 0.012839666035174722, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.6238446412853621, 'colsample_bytree': 0.48931362707095033, 'reg_alpha': 0.009259257365774149, 'reg_lambda': 0.6555104652602122, 'gamma': 0.02513195844549469}.

plan trial 77/100: COMPLETE

[I 2026-10-03 13:37:13,833] Trial 77 finished with values: [0.645478067989658, 0.10940101595853749] and parameters: {'learning_rate': 0.005517994026635822, 'max_depth': 6, 'min_child_weight': 16, 'subsample': 0.8886312817053952, 'colsample_bytree': 0.5518483265305354, 'reg_alpha': 0.24105770387322079, 'reg_lambda': 0.8599233219375855, 'gamma': 0.024220049272347582}.

plan trial 78/100: COMPLETE

[I 2026-10-03 13:38:01,333] Trial 78 finished with values: [0.6456024231853739, 0.10945457526093165] and parameters: {'learning_rate': 0.0042721879589528, 'max_depth': 9, 'min_child_weight': 15, 'subsample': 0.6192556002153113, 'colsample_bytree': 0.5990779833438986, 'reg_alpha': 0.021662321786466297, 'reg_lambda': 1.0394751471340036, 'gamma': 0.7381804070309487}.

plan trial 79/100: COMPLETE

[I 2026-10-03 13:38:24,926] Trial 79 finished with values: [0.6453799274074732, 0.1096472158985982] and parameters: {'learning_rate': 0.012839666035174722, 'max_depth': 9, 'min_child_weight': 6, 'subsample': 0.8972903510269807, 'colsample_bytree': 0.48931362707095033, 'reg_alpha': 0.0398615832269852, 'reg_lambda': 0.1667601645056436, 'gamma': 0.02513195844549469}.

plan trial 80/100: COMPLETE

[I 2026-10-03 13:38:55,350] Trial 80 finished with values: [0.6468001009902343, 0.10942724833914035] and parameters: {'learning_rate': 0.012839666035174722, 'max_depth': 5, 'min_child_weight': 7, 'subsample': 0.7302000895830555, 'colsample_bytree': 0.48931362707095033, 'reg_alpha': 0.001307356307358973, 'reg_lambda': 0.13143853758621094, 'gamma': 1.609183966912419}.

plan trial 81/100: COMPLETE

[I 2026-10-03 13:39:23,135] Trial 81 finished with values: [0.6450295159870838, 0.10943998694293615] and parameters: {'learning_rate': 0.01689423858576688, 'max_depth': 4, 'min_child_weight': 11, 'subsample': 0.886097910041558, 'colsample_bytree': 0.4343454392497529, 'reg_alpha': 0.015101927098715837, 'reg_lambda': 0.4254455661099687, 'gamma': 0.12856626346725913}.

plan trial 82/100: COMPLETE

[I 2026-10-03 13:39:44,531] Trial 82 finished with values: [0.6451469273493314, 0.10970021868235111] and parameters: {'learning_rate': 0.012839666035174722, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.7302000895830555, 'colsample_bytree': 0.6555765515825789, 'reg_alpha': 0.009259257365774149, 'reg_lambda': 0.13143853758621094, 'gamma': 1.6917868153871534}.

plan trial 83/100: COMPLETE

[I 2026-10-03 13:40:17,177] Trial 83 finished with values: [0.6451421579650278, 0.10944434256098001] and parameters: {'learning_rate': 0.01689423858576688, 'max_depth': 4, 'min_child_weight': 30, 'subsample': 0.886097910041558, 'colsample_bytree': 0.43475205509889525, 'reg_alpha': 0.0030865085370801165, 'reg_lambda': 0.4254455661099687, 'gamma': 0.039541210999596975}.

plan trial 84/100: COMPLETE

[I 2026-10-03 13:40:49,194] Trial 84 finished with values: [0.6454453733145356, 0.10941738835980933] and parameters: {'learning_rate': 0.012839666035174722, 'max_depth': 4, 'min_child_weight': 7, 'subsample': 0.7537325567323934, 'colsample_bytree': 0.662670111614476, 'reg_alpha': 0.5828273075340881, 'reg_lambda': 0.21644033624761616, 'gamma': 0.02513195844549469}.

plan trial 85/100: COMPLETE

[I 2026-10-03 13:41:37,235] Trial 85 finished with values: [0.6454253869547115, 0.10940969546487207] and parameters: {'learning_rate': 0.004370881039092839, 'max_depth': 7, 'min_child_weight': 18, 'subsample': 0.7923362721592008, 'colsample_bytree': 0.5932035485965139, 'reg_alpha': 0.5074214867727057, 'reg_lambda': 0.4466285489787785, 'gamma': 1.0128566184663834}.

plan trial 86/100: COMPLETE

[I 2026-10-03 13:42:01,173] Trial 86 finished with values: [0.6456888948460217, 0.10953082238619576] and parameters: {'learning_rate': 0.01243386731799552, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.627647032110041, 'colsample_bytree': 0.46757894269245187, 'reg_alpha': 0.6092511003337083, 'reg_lambda': 0.20756284766202893, 'gamma': 0.0829340446620956}.

plan trial 87/100: COMPLETE

[I 2026-10-03 13:42:21,632] Trial 87 finished with values: [0.6442223573025186, 0.10968377018884823] and parameters: {'learning_rate': 0.017605714927279803, 'max_depth': 9, 'min_child_weight': 15, 'subsample': 0.6192556002153113, 'colsample_bytree': 0.42864318009804186, 'reg_alpha': 0.00572380548021796, 'reg_lambda': 1.163792213611752, 'gamma': 0.014692798156764731}.

plan trial 88/100: COMPLETE

[I 2026-10-03 13:42:40,890] Trial 88 finished with values: [0.645241327887887, 0.10950221105011386] and parameters: {'learning_rate': 0.02485676889228442, 'max_depth': 6, 'min_child_weight': 18, 'subsample': 0.723327121538445, 'colsample_bytree': 0.4555858681282208, 'reg_alpha': 0.8237691529375192, 'reg_lambda': 3.9312157314519167, 'gamma': 0.2295819372628562}.

plan trial 89/100: COMPLETE

[I 2026-10-03 13:43:26,178] Trial 89 finished with values: [0.645966033133271, 0.10942121420683588] and parameters: {'learning_rate': 0.004910136343876599, 'max_depth': 8, 'min_child_weight': 20, 'subsample': 0.8202280631532665, 'colsample_bytree': 0.43208947692495325, 'reg_alpha': 0.4286906704972381, 'reg_lambda': 0.29436711236801544, 'gamma': 0.26995438263879673}.

plan trial 90/100: COMPLETE

[I 2026-10-03 13:43:45,042] Trial 90 finished with values: [0.6449277669800515, 0.109672076475602] and parameters: {'learning_rate': 0.0262819126381573, 'max_depth': 9, 'min_child_weight': 12, 'subsample': 0.8616045805437124, 'colsample_bytree': 0.4101445810148692, 'reg_alpha': 0.045395681857058966, 'reg_lambda': 8.716538801681102, 'gamma': 0.7381804070309487}.

plan trial 91/100: COMPLETE

[I 2026-10-03 13:44:30,240] Trial 91 finished with values: [0.6454135238460181, 0.10946191824987943] and parameters: {'learning_rate': 0.004910136343876599, 'max_depth': 8, 'min_child_weight': 20, 'subsample': 0.6192556002153113, 'colsample_bytree': 0.43208947692495325, 'reg_alpha': 0.34786969074571267, 'reg_lambda': 0.9565507076785098, 'gamma': 0.26995438263879673}.

plan trial 92/100: COMPLETE

[I 2026-10-03 13:44:58,323] Trial 92 finished with values: [0.6450298955564877, 0.10958528085709018] and parameters: {'learning_rate': 0.01098610678602083, 'max_depth': 9, 'min_child_weight': 28, 'subsample': 0.8010586865947888, 'colsample_bytree': 0.4101445810148692, 'reg_alpha': 0.1584237947311508, 'reg_lambda': 0.49521885180909386, 'gamma': 0.05776934970095832}.

plan trial 93/100: COMPLETE

[I 2026-10-03 13:45:39,677] Trial 93 finished with values: [0.6436735755235266, 0.10939863629901361] and parameters: {'learning_rate': 0.004370881039092839, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6395345367575241, 'colsample_bytree': 0.5932035485965139, 'reg_alpha': 0.1436757127036174, 'reg_lambda': 0.7578459397323387, 'gamma': 0.0829340446620956}.

plan trial 94/100: COMPLETE

[I 2026-10-03 13:46:07,357] Trial 94 finished with values: [0.6449291439487849, 0.10943414798309707] and parameters: {'learning_rate': 0.012133145372404076, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.8972903510269807, 'colsample_bytree': 0.5193064189048473, 'reg_alpha': 0.0398615832269852, 'reg_lambda': 1.1840859322116128, 'gamma': 0.46512564796488876}.

plan trial 95/100: COMPLETE

[I 2026-10-03 13:46:25,548] Trial 95 finished with values: [0.6452337816124762, 0.10956045428238778] and parameters: {'learning_rate': 0.022260728588262314, 'max_depth': 7, 'min_child_weight': 5, 'subsample': 0.6783588190263752, 'colsample_bytree': 0.4763936303773111, 'reg_alpha': 0.00572380548021796, 'reg_lambda': 1.9682101437034563, 'gamma': 0.058101306745059283}.

plan trial 96/100: COMPLETE

[I 2026-10-03 13:46:42,920] Trial 96 finished with values: [0.6445962820318922, 0.10954637868994321] and parameters: {'learning_rate': 0.023985139569256908, 'max_depth': 7, 'min_child_weight': 26, 'subsample': 0.7235627542430807, 'colsample_bytree': 0.6675350883103686, 'reg_alpha': 0.061135212596469264, 'reg_lambda': 1.9682101437034563, 'gamma': 0.014692798156764731}.

plan trial 97/100: COMPLETE

[I 2026-10-03 13:47:34,953] Trial 97 finished with values: [0.6461508026572789, 0.10952569908223952] and parameters: {'learning_rate': 0.0032697595311624037, 'max_depth': 9, 'min_child_weight': 5, 'subsample': 0.6041369670320651, 'colsample_bytree': 0.662670111614476, 'reg_alpha': 0.01047886223833977, 'reg_lambda': 0.21644033624761616, 'gamma': 0.03636309175058783}.

plan trial 98/100: COMPLETE

[I 2026-10-03 13:48:10,709] Trial 98 finished with values: [0.6455221539623341, 0.109464778526391] and parameters: {'learning_rate': 0.007338959702060606, 'max_depth': 7, 'min_child_weight': 28, 'subsample': 0.7532278886361137, 'colsample_bytree': 0.5007216146480863, 'reg_alpha': 0.18888780864812524, 'reg_lambda': 0.7412576614964576, 'gamma': 0.026560847322503172}.

plan trial 99/100: COMPLETE

[I 2026-10-03 13:48:10,766] Trial 99 finished with values: [0.6457230348473163, 0.10938978373226846] and parameters: {'learning_rate': 0.006731222648259909, 'max_depth': 5, 'min_child_weight': 5, 'subsample': 0.7139277498525687, 'colsample_bytree': 0.4977613276410141, 'reg_alpha': 0.2961438123248616, 'reg_lambda': 2.634563107932524, 'gamma': 0.18709665744346862}.

plan trial 100/100: COMPLETE

[I 2026-10-03 13:58:25,514] A new study created in memory with name: readmission_dual_f53816455a8a

C:\Users\andre\miniconda3\envs\surv\Lib\site-packages\optuna\trial\_trial.py:658: UserWarning: Fixed parameter 'colsample_bytree' with value 0.4101445810148692 is out of range for distribution FloatDistribution(high=0.66, log=False, low=0.45, step=None).
  optuna_warn(
C:\Users\andre\miniconda3\envs\surv\Lib\site-packages\optuna\trial\_trial.py:658: UserWarning: Fixed parameter 'gamma' with value 0.03636309175058783 is out of range for distribution FloatDistribution(high=2.0, log=False, low=0.2, step=None).
  optuna_warn(

[I 2026-10-03 13:59:16,140] Trial 0 finished with values: [0.6459756366353512, 0.10952022760718325] and parameters: {'learning_rate': 0.003937534064623471, 'max_depth': 9, 'min_child_weight': 10, 'subsample': 0.8272160609666579, 'colsample_bytree': 0.4101445810148692, 'reg_alpha': 0.0012689920611310094, 'reg_lambda': 0.12594597985355963, 'gamma': 0.03636309175058783}.

dual trial 1/50: COMPLETE

C:\Users\andre\miniconda3\envs\surv\Lib\site-packages\optuna\trial\_trial.py:658: UserWarning: Fixed parameter 'learning_rate' with value 0.012839666035174722 is out of range for distribution FloatDistribution(high=0.012, log=True, low=0.0025, step=None).
  optuna_warn(

[I 2026-10-03 13:59:42,400] Trial 1 finished with values: [0.6442121711677047, 0.1095163903061109] and parameters: {'learning_rate': 0.012839666035174722, 'max_depth': 5, 'min_child_weight': 7, 'subsample': 0.7302000895830555, 'colsample_bytree': 0.48931362707095033, 'reg_alpha': 0.001307356307358973, 'reg_lambda': 0.13143853758621094, 'gamma': 1.609183966912419}.

dual trial 2/50: COMPLETE

C:\Users\andre\miniconda3\envs\surv\Lib\site-packages\optuna\trial\_trial.py:658: UserWarning: Fixed parameter 'learning_rate' with value 0.012839666035174722 is out of range for distribution FloatDistribution(high=0.012, log=True, low=0.0025, step=None).
  optuna_warn(
C:\Users\andre\miniconda3\envs\surv\Lib\site-packages\optuna\trial\_trial.py:658: UserWarning: Fixed parameter 'gamma' with value 0.02513195844549469 is out of range for distribution FloatDistribution(high=2.0, log=False, low=0.2, step=None).
  optuna_warn(

[I 2026-10-03 14:00:09,663] Trial 2 finished with values: [0.6441703658652725, 0.10947495372313706] and parameters: {'learning_rate': 0.012839666035174722, 'max_depth': 5, 'min_child_weight': 7, 'subsample': 0.7302000895830555, 'colsample_bytree': 0.48931362707095033, 'reg_alpha': 0.009259257365774149, 'reg_lambda': 0.13143853758621094, 'gamma': 0.02513195844549469}.

dual trial 3/50: COMPLETE

C:\Users\andre\miniconda3\envs\surv\Lib\site-packages\optuna\trial\_trial.py:658: UserWarning: Fixed parameter 'gamma' with value 0.18709665744346862 is out of range for distribution FloatDistribution(high=2.0, log=False, low=0.2, step=None).
  optuna_warn(

[I 2026-10-03 14:00:49,384] Trial 3 finished with values: [0.6437148643352202, 0.10946270690173565] and parameters: {'learning_rate': 0.006731222648259909, 'max_depth': 5, 'min_child_weight': 5, 'subsample': 0.7139277498525687, 'colsample_bytree': 0.4977613276410141, 'reg_alpha': 0.2961438123248616, 'reg_lambda': 2.634563107932524, 'gamma': 0.18709665744346862}.

dual trial 4/50: COMPLETE

[I 2026-10-03 14:01:37,947] Trial 4 finished with values: [0.6450836620493794, 0.1094694956440854] and parameters: {'learning_rate': 0.0035682692429742312, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.590077079892864, 'colsample_bytree': 0.6209675619540531, 'reg_alpha': 0.06470411597431235, 'reg_lambda': 0.47760229145231975, 'gamma': 0.9186864692832424}.

dual trial 5/50: COMPLETE

[I 2026-10-03 14:02:19,656] Trial 5 finished with values: [0.6438886033383373, 0.10955847455536483] and parameters: {'learning_rate': 0.005554067452852061, 'max_depth': 9, 'min_child_weight': 25, 'subsample': 0.696214353948697, 'colsample_bytree': 0.56510231997221, 'reg_alpha': 0.6296616760669812, 'reg_lambda': 1.4423995796044764, 'gamma': 1.2646049351122028}.

dual trial 6/50: COMPLETE

[I 2026-10-03 14:03:03,273] Trial 6 finished with values: [0.6441207037875081, 0.10952031495613401] and parameters: {'learning_rate': 0.00505693651864707, 'max_depth': 7, 'min_child_weight': 25, 'subsample': 0.6945541029919505, 'colsample_bytree': 0.6007395430791329, 'reg_alpha': 0.00063140367705649, 'reg_lambda': 0.17878045486188116, 'gamma': 1.1841021411747221}.

dual trial 7/50: COMPLETE

[I 2026-10-03 14:03:51,399] Trial 7 finished with values: [0.6446152964461808, 0.10951085700842225] and parameters: {'learning_rate': 0.004089898512236412, 'max_depth': 8, 'min_child_weight': 20, 'subsample': 0.8189555466608042, 'colsample_bytree': 0.4724626338474673, 'reg_alpha': 0.26885279800825407, 'reg_lambda': 1.5230733156407439, 'gamma': 1.319638897969193}.

dual trial 8/50: COMPLETE

[I 2026-10-03 14:04:25,639] Trial 8 finished with values: [0.6432942688042345, 0.10957280604067414] and parameters: {'learning_rate': 0.006359039778695261, 'max_depth': 9, 'min_child_weight': 28, 'subsample': 0.5717303227802437, 'colsample_bytree': 0.6219068833965204, 'reg_alpha': 0.0019436801196345648, 'reg_lambda': 3.075732418381726, 'gamma': 1.2804724890228725}.

dual trial 9/50: COMPLETE

[I 2026-10-03 14:04:49,690] Trial 9 finished with values: [0.6430995705338229, 0.1096092655572412] and parameters: {'learning_rate': 0.011760892429612844, 'max_depth': 9, 'min_child_weight': 26, 'subsample': 0.6083330491374173, 'colsample_bytree': 0.643367235473566, 'reg_alpha': 0.00021893731351470714, 'reg_lambda': 0.5608010177813877, 'gamma': 1.5483533729884178}.

dual trial 10/50: COMPLETE

[I 2026-10-03 14:05:43,525] Trial 10 finished with values: [0.6453510915500924, 0.1095520686895062] and parameters: {'learning_rate': 0.0035279285171762272, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.7989317071281026, 'colsample_bytree': 0.49946471522290825, 'reg_alpha': 0.39873160734492086, 'reg_lambda': 0.2281488784800009, 'gamma': 1.8134179480806518}.

dual trial 11/50: COMPLETE

[I 2026-10-03 14:06:34,042] Trial 11 finished with values: [0.645636253089458, 0.10959022156088596] and parameters: {'learning_rate': 0.003623863625979117, 'max_depth': 9, 'min_child_weight': 6, 'subsample': 0.8278070105577668, 'colsample_bytree': 0.49794766437157134, 'reg_alpha': 0.00013639558292864457, 'reg_lambda': 0.11949388892426281, 'gamma': 0.6385816113039309}.

dual trial 12/50: COMPLETE

[I 2026-10-03 14:07:12,431] Trial 12 finished with values: [0.6438661494689619, 0.10946904883214195] and parameters: {'learning_rate': 0.006714729325914949, 'max_depth': 5, 'min_child_weight': 7, 'subsample': 0.9165677779675089, 'colsample_bytree': 0.5335144932333932, 'reg_alpha': 0.012173619870656759, 'reg_lambda': 0.6740441840522661, 'gamma': 1.5044708344244155}.

dual trial 13/50: COMPLETE

[I 2026-10-03 14:07:48,201] Trial 13 finished with values: [0.6443336103489499, 0.10946455243940534] and parameters: {'learning_rate': 0.006842321174914736, 'max_depth': 6, 'min_child_weight': 16, 'subsample': 0.8820624492900883, 'colsample_bytree': 0.584211738514352, 'reg_alpha': 0.002335575830644817, 'reg_lambda': 1.3480712404369086, 'gamma': 0.977658440196947}.

dual trial 14/50: COMPLETE

[I 2026-10-03 14:08:31,074] Trial 14 finished with values: [0.6425989810383153, 0.10950528646931515] and parameters: {'learning_rate': 0.004195476121384499, 'max_depth': 6, 'min_child_weight': 29, 'subsample': 0.5602796095726781, 'colsample_bytree': 0.5284928681872283, 'reg_alpha': 0.9690946744746047, 'reg_lambda': 2.0698273859828245, 'gamma': 1.7868766248696024}.

dual trial 15/50: COMPLETE

[I 2026-10-03 14:09:00,316] Trial 15 finished with values: [0.6449791491935086, 0.1095929264604251] and parameters: {'learning_rate': 0.009364284939563844, 'max_depth': 7, 'min_child_weight': 6, 'subsample': 0.8734024496435322, 'colsample_bytree': 0.5034755412641178, 'reg_alpha': 0.051994280383185994, 'reg_lambda': 0.27205318263733225, 'gamma': 0.7977908253388677}.

dual trial 16/50: COMPLETE

[I 2026-10-03 14:09:42,831] Trial 16 finished with values: [0.6434015737590852, 0.10945636507862935] and parameters: {'learning_rate': 0.004280062353424585, 'max_depth': 6, 'min_child_weight': 19, 'subsample': 0.848043575470457, 'colsample_bytree': 0.5653493126269983, 'reg_alpha': 0.030797667377073547, 'reg_lambda': 1.634258818032068, 'gamma': 0.8071544017721026}.

dual trial 17/50: COMPLETE

[I 2026-10-03 14:10:20,561] Trial 17 finished with values: [0.6432091849897205, 0.10946235863164422] and parameters: {'learning_rate': 0.008050416946353254, 'max_depth': 4, 'min_child_weight': 11, 'subsample': 0.9023906860526403, 'colsample_bytree': 0.47404180747482705, 'reg_alpha': 0.06891059760547807, 'reg_lambda': 0.305836252925171, 'gamma': 0.6670473400275285}.

dual trial 18/50: COMPLETE

[I 2026-10-03 14:10:50,102] Trial 18 finished with values: [0.6439235328919476, 0.10954413322450647] and parameters: {'learning_rate': 0.008234488545049014, 'max_depth': 7, 'min_child_weight': 26, 'subsample': 0.6392545041000752, 'colsample_bytree': 0.6372745618172581, 'reg_alpha': 0.0009709898717699662, 'reg_lambda': 0.9978544505520595, 'gamma': 0.33071890546788396}.

dual trial 19/50: COMPLETE

[I 2026-10-03 14:11:33,549] Trial 19 finished with values: [0.6440738402465496, 0.10942345666768091] and parameters: {'learning_rate': 0.00392114958910248, 'max_depth': 6, 'min_child_weight': 8, 'subsample': 0.6490061222991431, 'colsample_bytree': 0.5624029343269792, 'reg_alpha': 0.12698447673645208, 'reg_lambda': 0.5265440408940972, 'gamma': 1.658138161016928}.

dual trial 20/50: COMPLETE

[I 2026-10-03 14:12:12,161] Trial 20 finished with values: [0.6442807685837708, 0.1094771635989467] and parameters: {'learning_rate': 0.00634367334127964, 'max_depth': 6, 'min_child_weight': 11, 'subsample': 0.6736376039972513, 'colsample_bytree': 0.6414060488505388, 'reg_alpha': 0.028364605136469424, 'reg_lambda': 3.234691341827221, 'gamma': 1.8029450540334766}.

dual trial 21/50: COMPLETE

[I 2026-10-03 14:12:38,986] Trial 21 finished with values: [0.644246448833356, 0.10952937448969416] and parameters: {'learning_rate': 0.011344402590505365, 'max_depth': 6, 'min_child_weight': 15, 'subsample': 0.5743868455435095, 'colsample_bytree': 0.4559373319437319, 'reg_alpha': 0.11798485788116339, 'reg_lambda': 1.2036086985632581, 'gamma': 1.1258989206302965}.

dual trial 22/50: COMPLETE

[I 2026-10-03 14:13:25,102] Trial 22 finished with values: [0.6453396602093268, 0.10955141869137923] and parameters: {'learning_rate': 0.0047624744395839995, 'max_depth': 9, 'min_child_weight': 10, 'subsample': 0.8713658020220356, 'colsample_bytree': 0.4571012067104085, 'reg_alpha': 0.005499684811497841, 'reg_lambda': 0.6095580728198908, 'gamma': 1.661385784315836}.

dual trial 23/50: COMPLETE

[I 2026-10-03 14:14:02,264] Trial 23 finished with values: [0.642726191288832, 0.10951051609433768] and parameters: {'learning_rate': 0.006888409798580569, 'max_depth': 5, 'min_child_weight': 28, 'subsample': 0.7133292080039879, 'colsample_bytree': 0.5843715180413656, 'reg_alpha': 0.0007049405773398852, 'reg_lambda': 0.594277097044777, 'gamma': 0.7762982115654491}.

dual trial 24/50: COMPLETE

[I 2026-10-03 14:14:52,338] Trial 24 finished with values: [0.6445792123272144, 0.10951421633579243] and parameters: {'learning_rate': 0.0037895436684744184, 'max_depth': 9, 'min_child_weight': 15, 'subsample': 0.5643904269393945, 'colsample_bytree': 0.4700502260686293, 'reg_alpha': 0.2047870708279346, 'reg_lambda': 0.665107903566421, 'gamma': 0.7668462195684427}.

dual trial 25/50: COMPLETE

[I 2026-10-03 14:15:33,441] Trial 25 finished with values: [0.6443164809375597, 0.10951477341462668] and parameters: {'learning_rate': 0.0057734257510642095, 'max_depth': 7, 'min_child_weight': 30, 'subsample': 0.8564994397267129, 'colsample_bytree': 0.5726862646353521, 'reg_alpha': 0.009890846820173955, 'reg_lambda': 1.118437703606684, 'gamma': 0.5484006421170292}.

dual trial 26/50: COMPLETE

[I 2026-10-03 14:16:19,149] Trial 26 finished with values: [0.6443707892401498, 0.10950560664424916] and parameters: {'learning_rate': 0.004360052073920011, 'max_depth': 7, 'min_child_weight': 17, 'subsample': 0.8801208527321769, 'colsample_bytree': 0.5562938285713748, 'reg_alpha': 0.00044994385536554376, 'reg_lambda': 0.6668526341492524, 'gamma': 0.500524131140963}.

dual trial 27/50: COMPLETE

[I 2026-10-03 14:16:44,654] Trial 27 finished with values: [0.643866761073171, 0.10955613193336951] and parameters: {'learning_rate': 0.010766659083246505, 'max_depth': 7, 'min_child_weight': 16, 'subsample': 0.5472500899640508, 'colsample_bytree': 0.507344460154262, 'reg_alpha': 0.010995873295049955, 'reg_lambda': 0.6214275149856036, 'gamma': 0.22872322437648732}.

dual trial 28/50: COMPLETE

[I 2026-10-03 14:17:24,605] Trial 28 finished with values: [0.6421150469237862, 0.10943097451933397] and parameters: {'learning_rate': 0.003837273706912728, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6873394638990076, 'colsample_bytree': 0.5852424840175597, 'reg_alpha': 0.0011927429209402417, 'reg_lambda': 0.3175270987879935, 'gamma': 0.4953468819040882}.

dual trial 29/50: COMPLETE

[I 2026-10-03 14:17:58,562] Trial 29 finished with values: [0.6441050315963347, 0.10945948376903454] and parameters: {'learning_rate': 0.00975512560490584, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.6965128220412355, 'colsample_bytree': 0.6338690781301333, 'reg_alpha': 0.002135028900360838, 'reg_lambda': 0.18150663246800497, 'gamma': 1.4701875238246531}.

dual trial 30/50: COMPLETE

[I 2026-10-03 14:18:41,747] Trial 30 finished with values: [0.6436248230743455, 0.10945733696697091] and parameters: {'learning_rate': 0.0047486161574408535, 'max_depth': 6, 'min_child_weight': 19, 'subsample': 0.8153889619245693, 'colsample_bytree': 0.6332740980241196, 'reg_alpha': 0.01281406220635118, 'reg_lambda': 0.9826217962762344, 'gamma': 0.5421877802624566}.

dual trial 31/50: COMPLETE

[I 2026-10-03 14:19:22,748] Trial 31 finished with values: [0.6408647135177568, 0.10945547245673246] and parameters: {'learning_rate': 0.0029167180119251887, 'max_depth': 5, 'min_child_weight': 16, 'subsample': 0.8074758753766649, 'colsample_bytree': 0.5736789054377401, 'reg_alpha': 0.00014179269599508948, 'reg_lambda': 0.5342767051540522, 'gamma': 0.8807690493089821}.

dual trial 32/50: COMPLETE

[I 2026-10-03 14:20:00,524] Trial 32 finished with values: [0.6404507236945981, 0.1095182242909426] and parameters: {'learning_rate': 0.00486660403064126, 'max_depth': 4, 'min_child_weight': 30, 'subsample': 0.7446044229170585, 'colsample_bytree': 0.5129958600942109, 'reg_alpha': 0.00958767733178736, 'reg_lambda': 2.0497212540987495, 'gamma': 1.8183722652429228}.

dual trial 33/50: COMPLETE

[I 2026-10-03 14:20:46,424] Trial 33 finished with values: [0.6420136446906473, 0.10946885276157517] and parameters: {'learning_rate': 0.004458375451553539, 'max_depth': 5, 'min_child_weight': 25, 'subsample': 0.6774153391547655, 'colsample_bytree': 0.5847960352190642, 'reg_alpha': 0.46062365744081807, 'reg_lambda': 0.8252139302908156, 'gamma': 0.4848006047340701}.

dual trial 34/50: COMPLETE

[I 2026-10-03 14:21:29,677] Trial 34 finished with values: [0.6419261681447666, 0.10944588918156302] and parameters: {'learning_rate': 0.00330071056475047, 'max_depth': 6, 'min_child_weight': 27, 'subsample': 0.8979512535007139, 'colsample_bytree': 0.5590461098265915, 'reg_alpha': 0.13582330934017978, 'reg_lambda': 0.2894031357652554, 'gamma': 0.5615920112718118}.

dual trial 35/50: COMPLETE

[I 2026-10-03 14:22:18,482] Trial 35 finished with values: [0.645266192176319, 0.10951591158412177] and parameters: {'learning_rate': 0.004614641100151235, 'max_depth': 8, 'min_child_weight': 13, 'subsample': 0.8373874578958251, 'colsample_bytree': 0.5038773529921384, 'reg_alpha': 0.0786588611982022, 'reg_lambda': 2.4562155043602236, 'gamma': 1.6627511039468137}.

dual trial 36/50: COMPLETE

[I 2026-10-03 14:22:45,986] Trial 36 finished with values: [0.64443824929823, 0.1096767421330318] and parameters: {'learning_rate': 0.010256479877783817, 'max_depth': 9, 'min_child_weight': 12, 'subsample': 0.8540824188425514, 'colsample_bytree': 0.5340304827082047, 'reg_alpha': 0.014420605246990473, 'reg_lambda': 3.14783264549628, 'gamma': 0.2426905001331534}.

dual trial 37/50: COMPLETE

[I 2026-10-03 14:23:28,755] Trial 37 finished with values: [0.6436778350053348, 0.10948380165576002] and parameters: {'learning_rate': 0.00462826832076372, 'max_depth': 7, 'min_child_weight': 29, 'subsample': 0.7340886589390773, 'colsample_bytree': 0.5205051302536604, 'reg_alpha': 0.09241606530466616, 'reg_lambda': 0.15273036476096982, 'gamma': 0.5318668019126224}.

dual trial 38/50: COMPLETE

[I 2026-10-03 14:24:14,435] Trial 38 finished with values: [0.6439024194476757, 0.10952887453819175] and parameters: {'learning_rate': 0.003932489611411473, 'max_depth': 9, 'min_child_weight': 18, 'subsample': 0.7027001252280356, 'colsample_bytree': 0.6289035861078053, 'reg_alpha': 0.1013213022218813, 'reg_lambda': 0.12666988759322875, 'gamma': 0.8304339105892993}.

dual trial 39/50: COMPLETE

[I 2026-10-03 14:24:56,288] Trial 39 finished with values: [0.6445612737626238, 0.10948360137997144] and parameters: {'learning_rate': 0.005097636811412658, 'max_depth': 7, 'min_child_weight': 15, 'subsample': 0.5911447197552778, 'colsample_bytree': 0.5969106758255058, 'reg_alpha': 0.07337348487859953, 'reg_lambda': 0.4695110489479342, 'gamma': 0.5436438404969541}.

dual trial 40/50: COMPLETE

[I 2026-10-03 14:25:40,410] Trial 40 finished with values: [0.6429261566228229, 0.10947984045492817] and parameters: {'learning_rate': 0.0045297242598887795, 'max_depth': 6, 'min_child_weight': 29, 'subsample': 0.7878655265690709, 'colsample_bytree': 0.6427706747090332, 'reg_alpha': 0.27209090003420033, 'reg_lambda': 0.2638341579711125, 'gamma': 1.5559357879681461}.

dual trial 41/50: COMPLETE

[I 2026-10-03 14:26:27,604] Trial 41 finished with values: [0.6436957286544454, 0.10950260608454714] and parameters: {'learning_rate': 0.003696008704836361, 'max_depth': 8, 'min_child_weight': 23, 'subsample': 0.7248987766457199, 'colsample_bytree': 0.5573392236554845, 'reg_alpha': 0.010336257556450477, 'reg_lambda': 0.13383884616222932, 'gamma': 1.7938150181852384}.

dual trial 42/50: COMPLETE

[I 2026-10-03 14:27:07,065] Trial 42 finished with values: [0.6446821114071446, 0.10958856377634132] and parameters: {'learning_rate': 0.005170604034040037, 'max_depth': 9, 'min_child_weight': 12, 'subsample': 0.6455504034242527, 'colsample_bytree': 0.6107437331872041, 'reg_alpha': 0.0009461886497401908, 'reg_lambda': 0.4771396655298912, 'gamma': 1.7644540953201333}.

dual trial 43/50: COMPLETE

[I 2026-10-03 14:27:47,784] Trial 43 finished with values: [0.6429830879966671, 0.10943790658125671] and parameters: {'learning_rate': 0.004861776248051154, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.6843084831465871, 'colsample_bytree': 0.5184329293487099, 'reg_alpha': 0.166038643840434, 'reg_lambda': 1.2497852058791536, 'gamma': 1.1950843126858466}.

dual trial 44/50: COMPLETE

[I 2026-10-03 14:28:42,847] Trial 44 finished with values: [0.6426861716999046, 0.10951157571250984] and parameters: {'learning_rate': 0.002549970566906052, 'max_depth': 9, 'min_child_weight': 30, 'subsample': 0.5702032122947921, 'colsample_bytree': 0.5638454999863428, 'reg_alpha': 0.0045017180141036965, 'reg_lambda': 0.45856484061253255, 'gamma': 0.29165673731271063}.

dual trial 45/50: COMPLETE

[I 2026-10-03 14:29:32,311] Trial 45 finished with values: [0.6435652093371784, 0.10943181330883536] and parameters: {'learning_rate': 0.0025986359001667443, 'max_depth': 7, 'min_child_weight': 5, 'subsample': 0.767670414287345, 'colsample_bytree': 0.52762416064473, 'reg_alpha': 0.01065152413499756, 'reg_lambda': 0.8218010016815138, 'gamma': 0.5648945066232589}.

dual trial 46/50: COMPLETE

[I 2026-10-03 14:30:03,476] Trial 46 finished with values: [0.6444606556141393, 0.10956287841022247] and parameters: {'learning_rate': 0.006805433311811585, 'max_depth': 9, 'min_child_weight': 10, 'subsample': 0.5750195740060521, 'colsample_bytree': 0.4973052598847163, 'reg_alpha': 0.00028887769042405646, 'reg_lambda': 0.1757317755464574, 'gamma': 1.5100135518430995}.

dual trial 47/50: COMPLETE

[I 2026-10-03 14:30:37,292] Trial 47 finished with values: [0.6433566587121705, 0.10945320157883767] and parameters: {'learning_rate': 0.010032013662775374, 'max_depth': 4, 'min_child_weight': 10, 'subsample': 0.6410133111082362, 'colsample_bytree': 0.5519634855137556, 'reg_alpha': 0.00018839522479216814, 'reg_lambda': 0.33646073635643875, 'gamma': 0.9946302541666645}.

dual trial 48/50: COMPLETE

[I 2026-10-03 14:31:02,463] Trial 48 finished with values: [0.6441237849438082, 0.10947752607411129] and parameters: {'learning_rate': 0.011598844515693525, 'max_depth': 6, 'min_child_weight': 11, 'subsample': 0.5997913572406499, 'colsample_bytree': 0.6066934065416267, 'reg_alpha': 0.04991530996987038, 'reg_lambda': 2.049186941399157, 'gamma': 0.6352209865438183}.

dual trial 49/50: COMPLETE

[I 2026-10-03 14:31:30,791] Trial 49 finished with values: [0.6439123806325198, 0.1096096157049364] and parameters: {'learning_rate': 0.008981872361916741, 'max_depth': 9, 'min_child_weight': 26, 'subsample': 0.783538217200631, 'colsample_bytree': 0.5299423719481829, 'reg_alpha': 0.009430802008159196, 'reg_lambda': 0.12591702328365986, 'gamma': 1.265525200339976}.

dual trial 50/50: COMPLETE

Elapsed: 127.068 minutes

## Manuscript comparison and handoff
The final hyperparameter table contributes the XGBoost readmission entries of eTable 2. Its values are compared at the four decimals reported for continuous parameters, with integer depth and child weight. A changed published entry requires the user's checkpoint before proceeding to notebook 02.
Brier comparisons describe different probability calculations: the historical approximation and corrected net survival. They are not an isolated leakage-effect estimate. The complete held-out comparison required by the manuscript remains a later notebook.

In [13]:
#| label: readm-export-winner-and-comparison
#| message: false
t0 = time.perf_counter()
# Export only the final manuscript-facing hyperparameters and a reusable model-selection bundle.
parameter_comparison = pd.DataFrame()
if final_table is not None:
    winner = final_table.iloc[0]
    winner_params = native_params(winner)
    bundle_path = artifact_path("xgb_readm_winner", model_signature, ".pkl")
    parameter_comparison = pd.DataFrame([{"Parameter": name, "Historical": native_params(historical_winner)[name], "Development_pipeline": winner_params[name], "Difference": winner_params[name] - native_params(historical_winner)[name], "Reported_decimals": 0 if name in ("max_depth", "min_child_weight") else 4, "Classification": "substantial" if round(winner_params[name], 0 if name in ("max_depth", "min_child_weight") else 4) != round(native_params(historical_winner)[name], 0 if name in ("max_depth", "min_child_weight") else 4) else "unchanged_at_reported_precision"} for name in param_names])
    summary = {"trial_id": int(winner["trial_id"]), **{name: float(winner[name]) for name in ["C", "mean_Brier", "global_C", "Distance_to_Ideal"]}}
    save_pickle({"signature": model_signature, "contract": model_contract, "params": winner_params, "summary": summary, "comparison": parameter_comparison, "final_candidates": final_table, "manuscript_checkpoint_required": True}, bundle_path)
    artifact_date = bundle_path.name.removeprefix("xgb_readm_winner_").split("_")[0]
    table_path = table_dir / f"etable2_xgboost_readmission_{artifact_date}_{model_signature}.csv"
    manuscript_table = pd.DataFrame([{"Outcome": "Readmission", "Parameter": name, "Initial_search_lower": initial_ranges[name][1], "Initial_search_upper": initial_ranges[name][2], "Search_scale": "log" if initial_ranges[name][3] else "linear", "Selected_value": winner_params[name], "Trial": int(winner["trial_id"]), "Source_cell": "readm-export-winner-and-comparison"} for name in param_names])
    if table_path.exists():
        pd.testing.assert_frame_equal(pd.read_csv(table_path), manuscript_table, check_dtype=False)
    else:
        manuscript_table.to_csv(table_path, index=False)
        written.append(table_path)
    show_table(parameter_comparison, "eTable 2: historical versus development-imputed hyperparameters")
    metric_comparison = pd.DataFrame({"Metric": ["Mean horizon Uno C", "Mean horizon Brier", "Global Uno C"], "Historical": [float(historical_winner[c_column]), float(historical_winner[b_column]), float(historical_winner["Phase2_Global_C_Index"])], "Development_pipeline": [summary["C"], summary["mean_Brier"], summary["global_C"]]})
    metric_comparison["Difference"] = metric_comparison["Development_pipeline"] - metric_comparison["Historical"]
    show_table(metric_comparison, "Saved historical tuning references versus new final selection")
    # Keep the superseded fold-imputation run visible as a separate methodological reference.
    with source_path("xgboost_readmission_superseded_winner").open("rb") as stream:
        previous_fold_run = pickle.load(stream)
    assert previous_fold_run["signature"] != model_signature
    scope_comparison = pd.DataFrame({"Metric": ["Mean horizon Uno C", "Mean horizon Brier", "Global Uno C"], "Previous_fold_imputation": [previous_fold_run["summary"][name] for name in ["C", "mean_Brier", "global_C"]], "Development_imputation": [summary[name] for name in ["C", "mean_Brier", "global_C"]]})
    scope_comparison["Difference"] = scope_comparison["Development_imputation"] - scope_comparison["Previous_fold_imputation"]
    show_table(scope_comparison, "Imputation-scope change: superseded fold-wise run versus current development-imputed tuning")
    print("Review changed manuscript entries before adopting this winner. The user authorized both tuning notebooks; notebook 03 requires a checkpoint.")
else:
    print("Final eTable 2 entries and winner bundle are pending full tuning; no pilot metric is exported as a manuscript result.")
print(f"Elapsed: {(time.perf_counter() - t0) / 60:.3f} minutes")

Review changed manuscript entries before adopting this winner. The user authorized both tuning notebooks; notebook 03 requires a checkpoint.
Elapsed: 0.002 minutes

## Interpreting the hyperparameter changes
This section uses the selected parameters and cached final fold evaluations. It performs no additional model fitting.

In [14]:
#| label: readm-interpret-hyperparameter-changes
#| message: false
t0 = time.perf_counter()
# Interpret parameter directions without changing the selected model or fitting new models.
if final_table is None:
    print("Interpretation is pending full tuning or reuse of its complete saved results.")
else:
    direction_notes = {
        "learning_rate": ("Larger contribution from each new tree, holding other settings fixed.", "Smaller contribution from each new tree, holding other settings fixed."),
        "max_depth": ("A greater maximum tree depth is allowed.", "A smaller maximum tree depth is allowed."),
        "min_child_weight": ("More restrictive threshold for splitting a node.", "Less restrictive threshold for splitting a node."),
        "subsample": ("More training rows are sampled for each tree.", "Fewer training rows are sampled for each tree."),
        "colsample_bytree": ("More predictor columns are available to each tree.", "Fewer predictor columns are available to each tree."),
        "reg_alpha": ("Stronger L1 penalty on leaf weights.", "Weaker L1 penalty on leaf weights."),
        "reg_lambda": ("Stronger L2 penalty on leaf weights.", "Weaker L2 penalty on leaf weights."),
        "gamma": ("A larger loss reduction is required before splitting.", "A smaller loss reduction is sufficient before splitting.")}
    interpretation = parameter_comparison[["Parameter", "Historical", "Development_pipeline", "Difference", "Classification"]].copy()
    interpretation["Relative_change_percent"] = 100 * interpretation["Difference"] / interpretation["Historical"]
    interpretation["Interpretation"] = ["Unchanged." if row.Difference == 0 else direction_notes[row.Parameter][0 if row.Difference > 0 else 1] for row in interpretation.itertuples()]
    interpretation = interpretation.rename(columns={"Historical": "Previous", "Development_pipeline": "Updated", "Relative_change_percent": "Relative change (%)"})
    show_table(interpretation[["Parameter", "Previous", "Updated", "Relative change (%)", "Interpretation", "Classification"]], "Direction and magnitude of the selected hyperparameter changes")
    # Describe the observed stopping behavior of the winning configuration using cached final evaluations.
    selected_runs = [row for row in score_cache["scores"].values() if row["scheme"] == "dual" and row["params"] == winner_params]
    assert len(selected_runs) == model_contract["budgets"]["folds"] * model_contract["budgets"]["imputations"]
    rounds = np.asarray([row["returned_rounds"] for row in selected_runs])
    show_table(pd.DataFrame([{"Final fold/imputation evaluations": len(selected_runs), "Minimum returned rounds": int(rounds.min()), "Median returned rounds": float(np.median(rounds)), "Maximum returned rounds": int(rounds.max()), "Configured round limit": model_contract["rounds"], "Evaluations reaching the limit": int((rounds == model_contract["rounds"]).sum())}]), "Observed stopping behavior of the selected configuration")
    print("Relative parameter changes are not percentage changes in training speed, model complexity or predictive performance.")
print(f"Elapsed: {(time.perf_counter() - t0) / 60:.3f} minutes")

Relative parameter changes are not percentage changes in training speed, model complexity or predictive performance.
Elapsed: 0.000 minutes

The learning-rate change describes the contribution of a new tree, considered in isolation. It does not establish the convergence speed of the full model. Regularization, sampling, depth and child-weight changes act through different controls and cannot be added into one measure of complexity. Definitions follow the [official XGBoost parameter documentation](https://xgboost.readthedocs.io/en/release_3.1.0/parameter.html#parameters-for-tree-booster).
The stopping summary describes the new configuration only. Historical and updated learning curves have not been compared; stopping below the round limit is not proof of absence of overfitting.
Here, **substantial** means that a parameter changes at the reported precision of eTable 2. It does not mean substantial deterioration in prediction. Tuning comparisons do not establish stable SHAP rules, calibration or held-out performance.
The earlier fold-imputation winner was accepted before the investigator chose complete-development imputation. That earlier acceptance does not transfer to this new winner. Both tuning notebooks are authorized to run; changed manuscript entries require review before adoption and before notebook 03.
### Complete-development rerun checkpoint (2026-10-03)
The full run reused the five completed development datasets from notebook 00. It made no new imputation fits. The original participant split, CV memberships, search settings, selection rule and scoring implementation were retained. The superseded fold-imputation run is a separate historical comparator, not the manuscript baseline.
| Parameter | Superseded fold-imputation winner | Current complete-development winner | Classification |
|---|---:|---:|---|
| min_child_weight | 5 | 10 | Substantial: a different selected configuration |
| colsample_bytree | 0.468497 | 0.410145 | Substantial: a different selected configuration |
The learning rate and the other five parameters are identical to the superseded winner. The selected configuration changed, so adopting it for SHAP requires the investigator's checkpoint. Seven parameters still differ from the original manuscript table; the full manuscript comparison is displayed above.
| Internal tuning metric | Superseded fold-imputation run | Complete-development run | Difference |
|---|---:|---:|---:|
| C | 0.645939 | 0.646072 | +0.000133 |
| mean_Brier | 0.109552 | 0.109508 | -0.000044 |
| global_C | 0.616274 | 0.616199 | -0.000075 |
The tuning metrics remain close descriptively. These are comparisons of two selected winners, not a paired experiment with fixed parameters, an equivalence test or a held-out performance estimate. They do not establish stability of the Cox specifications, Tables 2-4 or eTables 11-15.
Imputation is shared across internal CV folds; this CV does not independently evaluate the whole preprocessing procedure. Holdout rows did not fit the imputers or tune this model. No claim of complete independence of historical discovery decisions is made.
Investigator decision: option A was accepted on 2026-10-03. Adopt this complete-development winner and proceed with the full mortality tuning in notebook 02. The additional fixed-parameter comparison was not requested. The original manuscript remains unchanged; notebook 03 and its SHAP work require the next checkpoint.

## Resources and execution status

In [15]:
#| label: readm-resource-and-status
#| message: false
t0 = time.perf_counter()
# Report current resources; the external runner records the sampled process-tree peak.
encoded_fold.cache_clear()
completed_development.cache_clear()
gc.collect()
show_table(pd.DataFrame({"Item": ["Mode", "Preflight controls", "New cohort model fits in this execution", "Full tuning complete", "Current Python RSS (GiB)", "Available RAM (GiB)", "Native threads", "Elapsed after setup (minutes)"], "Value": [mode, "passed", new_model_fits, final_table is not None, round(process.memory_info().rss / 2**30, 3), round(psutil.virtual_memory().available / 2**30, 3), threads, round((time.perf_counter() - run_started) / 60, 3)]}), "Execution status")
if mode == "preflight":
    print("Preflight estimates no tuning performance. Full mode runs the authorized search after its resource review.")
print(f"Elapsed: {(time.perf_counter() - t0) / 60:.3f} minutes")

Elapsed: 0.001 minutes

## Session info {#readm-execution-session}

In [16]:
#| label: readm-session-info
#| message: false
t0 = time.perf_counter()
# Record the actual Python environment and native thread limits.
package_names = ["numpy", "pandas", "xgboost", "optuna", "scikit-learn", "scikit-survival", "pyarrow", "PyYAML", "psutil", "threadpoolctl"]
show_table(pd.DataFrame({"Package": package_names, "Version": [importlib.metadata.version(name) for name in package_names]}), "Installed execution packages")
show_table(pd.DataFrame([{"Library": row.get("internal_api"), "Threads": row.get("num_threads"), "Version": row.get("version")} for row in threadpool_info()]), "Native thread pools")
assert all(row["num_threads"] <= threads for row in threadpool_info())
print("Imputation provenance: notebook 00 used R/r-main. This tuning session uses Python/surv only.")
print(f"Python {platform.python_version()} | {platform.system()} {platform.release()} | seed {seed}")
print(f"Elapsed since setup: {(time.perf_counter() - run_started) / 60:.3f} minutes")
print(f"Elapsed: {(time.perf_counter() - t0) / 60:.3f} minutes")

Imputation provenance: notebook 00 used R/r-main. This tuning session uses Python/surv only.
Python 3.11.14 | Windows 10 | seed 2125
Elapsed since setup: 127.172 minutes
Elapsed: 0.001 minutes

### Files written and execution status

In [17]:
#| label: readm-written-files-and-status
#| message: false
t0 = time.perf_counter()
# List only artifacts actually written or updated by this execution.
manifest = pd.DataFrame([{"Path": str(path.relative_to(root)).replace("\\", "/"), "Bytes": path.stat().st_size} for path in dict.fromkeys(written)], columns=["Path", "Bytes"])
show_table(manifest, "Files written in outputs")
execution_status = {"mode": mode, "imputation_fit_scope": "complete_development_before_cv", "new_imputation_fits": 0, "full_tuning_complete": final_table is not None, "new_model_fits": new_model_fits, "data_signature": data_signature, "model_signature": model_signature, "checkpoint_before_notebook_02": True}
print(json.dumps(execution_status, sort_keys=True))
print("Full tuning finished; review the comparison before notebook 02." if final_table is not None else "Preflight/pilot finished; full tuning and the notebook 01 checkpoint remain pending.")
print(f"Elapsed: {(time.perf_counter() - t0) / 60:.3f} minutes")

{"checkpoint_before_notebook_02": true, "data_signature": "93a86001d458", "full_tuning_complete": true, "imputation_fit_scope": "complete_development_before_cv", "mode": "full", "model_signature": "f53816455a8a", "new_imputation_fits": 0, "new_model_fits": 945}
Full tuning finished; review the comparison before notebook 02.
Elapsed: 0.001 minutes